### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#102]
@pdwaggoner Do you want to start with a working draft, or I can go ahead and create one?

Either way is fine by me.

**Comment by pdwaggoner** [comment]
Hi @IndrajeetPatil - thanks for starting the new issue to discuss. If you have the time, it might be more likely to happen faster. I am a bit underwater with a few things at the moment. I will of course contribute, or if you're OK with waiting for a while, I could start a draft later. Let me know what you'd prefer. Thanks!

**Comment by IndrajeetPatil** [comment]
Sounds good! Will get started with it then :)

**Comment by IndrajeetPatil** [comment]
@pdwaggoner First draft is ready. Can you please have a look? Thanks.

**Comment by pdwaggoner** [comment]
Brilliant, thanks @IndrajeetPatil ! Looks great. I have thoroughly edited and updated. Take a look and let me know what else you need/changes I should make.

**Comment by IndrajeetPatil** [comment]
Awesome! Looks fantastic now :)

**Comment by IndrajeetPatil** [comment]
The first draft of the paper is ready, when you get time, please edit it!

- [ ] @strengejacke 
- [ ] @mattansb  
- [ ] @bwiernik 
- [ ] @DominiqueMakowski

**Comment by IndrajeetPatil** [comment]
All needed docs are here: https://github.com/easystats/see/tree/master/paper

Make sure to edit `,Rmd` file, and **not** the `.md` file, like we had done in the past.

**Comment by strengejacke** [comment]
From now on, @pdwaggoner will be co-author for every English paper I'm writing. Your revisions to grammar/style of language always read so wonderfully smoothly. :-)

**Comment by IndrajeetPatil** [comment]
> co-author for every English paper 

Or even a book 😉 

> "Introduction to R: The easystats approach"

 (cf. https://twitter.com/patilindrajeets/status/1358112489825837056?s=20)

**Comment by pdwaggoner** [comment]
Yes! We need an easystats-focused version! Easystats shows up in a couple spots in the book, but I think a full scale treatment is overdue.

**Comment by IndrajeetPatil** [comment]
@bwiernik Can you please check if I've got your affiliation correctly and also if you have anything to add to the draft?

**Comment by bwiernik** [comment]
I'll take a look this week

**Comment by mattansb** [comment]
I've added some comments on the paper - I think the "Statement of Need" needs some work, I don't think the users interface and scope of use of the package is correctly laid out. Specifically, the package doesn't itself support many models - it supports the easystats packages which in turn support many models.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski's edits have addressed @mattansb's concerns.

@pdwaggoner Can you please do your stylistic magic on the manuscript one more time please?

**Comment by pdwaggoner** [comment]
Great changes and edits @mattansb and @DominiqueMakowski ! 

Per @IndrajeetPatil , I have gone back through and cleaned up the front end a bit. I omitted some redundancies and tried to streamline presentation of *see* in line with the *easystats* philosophy (all based, of course, on the most recent round of edits from @mattansb and @DominiqueMakowski ).

Let me know what else is needed. This paper is looking really good!

**Comment by IndrajeetPatil** [comment]
@pdwaggoner Thanks! Reads real smooth now.

> Of note: I haven't re-rendered the PDF. I have just been working from the .Rmd.

Done!

**Comment by IndrajeetPatil** [comment]
Once @bwiernik comments, I think we should be ready for submission.

**Comment by pdwaggoner** [comment]
@IndrajeetPatil thanks! I just made a few additional and minor edits/tinkering. Small changes, but the final version for submission should be rendered one more time. We can certainly do this once @bwiernik has commented/reviewed. Wanted to let you know the changes, though.

**Comment by IndrajeetPatil** [comment]
@bwiernik Do you think you can have a look at this by the end of the next week?

Now that the new release of `see` is out, this will be a good time to submit the paper.

**Comment by bwiernik** [comment]
Reading it right now.

**Comment by bwiernik** [comment]
For the model diagnostics, would it perhaps be nice to show `plot.see_check_model` with the multiple plots display? I think the six plots getting laid out together is really compelling.

**Comment by IndrajeetPatil** [comment]
Hmm, I had though about this but decided against doing so because we already include that very plot in the `performance` paper:
https://joss.theoj.org/papers/10.21105/joss.03139

So thought it might be better to avoid duplication.

**Comment by bwiernik** [comment]
Got it. That makes sense.

**Comment by bwiernik** [comment]
@IndrajeetPatil In https://github.com/easystats/see/pull/133, I made some stylistic edits for consistency and clarity and tweaked the Statement of Need section a bit to highlight better some of the limitations of existing tools, in particular the pretty heavy workflow to build a ggplot for a model from scratch. 

I have three broad comments:

1. There are some packages like *ggeffects* and *sjPlot* that do provide general model visualization tools (are they any not made by @strengejacke?). I think *see* has the advantage over these of the consistent `plot()` method that more tightly links the visualization with the actual modeling/checking functions. But do we need to mention this third class of existing ggplot extension packages?
2. For `plot.see_estimate_contrasts()`, could `estimate_mean()` be computed automatically if `data` is NULL, rather than giving a warning? That would make the explanation in the paper for this function easier.
3. It seems a little odd to me that a paper on a package for general model visualization wouldn't include a basic predicted line + uncertainty plot. As I was trying this out, I realized that there isn't currently a method for `plot.see_estimate_predicted`. Could a basic method for this be added @DominiqueMakowski? I think the paper would really benefit from having this functionality available at publication time.

**Comment by DominiqueMakowski** [comment]
2. should be feasible now, since we estimate_contrasts should have stored the info to run estimate_means() if not provided
3. Indeed, I'll look at [https://github.com/easystats/see/issues/38#issuecomment-850882416](https://github.com/easystats/see/issues/38#issuecomment-850882416) today

**Comment by pdwaggoner** [comment]
@bwiernik thanks for the revisions. In general I like it. But even though JOSS is a bit more informal of a journal, I am not a huge fan of informalities in academic papers like bulleted/numbered lists. Perhaps you might consider reformatting the process that's numbered at the outset of the paper in paragraph form with a bit more natural flow. I do like the inclusion of a sample code chunk to emphasize your point. But I think the text should be slightly more formal. Happy to defer to others though, if they think otherwise. Ping @IndrajeetPatil @DominiqueMakowski @strengejacke @mattansb

**Comment by bwiernik** [comment]
I don't really see how a numbered list is informal?

**Comment by strengejacke** [comment]
Can we re-render the PDF?

**Comment by IndrajeetPatil** [comment]
> Can we re-render the PDF?

I can do this tomorrow, unless someone can do it sooner. 

Traveling at the moment, and don’t have my windows machine on me.

**Comment by strengejacke** [comment]
You simply knit the rmd, or is there some automatisation?

**Comment by IndrajeetPatil** [comment]
Yes, just knit it.

if you are using pandoc 13.0, make sure to use the GitHub version of `rticles` package.

**Comment by strengejacke** [comment]
not sure which pandoc version I have (or where I can look this up) - I thought this is installed along with RStudio?

**Comment by IndrajeetPatil** [comment]
You can run:

`rmarkdown::pandoc_version()`

**Comment by strengejacke** [comment]
‘2.9.2.1’ - far away from 13.0

**Comment by IndrajeetPatil** [comment]
Lol, sorry I meant to write 2.13

**Comment by bwiernik** [comment]
Lol.

**Comment by IndrajeetPatil** [comment]
By the way, keep in mind that the pdf output is just for us. JOSS only cares about `.md` file. So don’t waste too much time on typesetting the pdf.

**Comment by bwiernik** [comment]
Okay. The page breaks were just to get the text and corresponding plot together on the same page.

**Comment by IndrajeetPatil** [comment]
@pdwaggoner Haven't forgotten about this. Just waiting for the next `modelbased` version to be on CRAN, and then all of us can work on this again.

We should be ready for a _JOSS_ submission pretty soon.

**Comment by pdwaggoner** [comment]
@IndrajeetPatil brilliant - sounds great and no rush from my end. Thanks again for leading the effort here. Let me know what you need from me.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski In light of the new `modelbased` version, can you please edit the `modelbased` paper of the section to address comments 2 and 3 here: https://github.com/easystats/see/issues/102#issuecomment-850888881

Then we can move on to styling edits and resolving other minor issues.

**Comment by strengejacke** [comment]
I wouldn't say lists are "informal", but I share @pdwaggoner reasoning about lists and try to avoid them if possible. That said, the revision from @bwiernik includes a code-chunk, so the "natural flow" is already "broken", and here the list may fit into the paragraph's text (non-)flow. If we want to keep the code example, we may also keep the list.

**Comment by DominiqueMakowski** [comment]
I've [added](https://github.com/easystats/see/commit/56e3de0eee89eb4f2e0e02f85732aa246e446072) a section to set the theme globally (so that, conveniently, the subsequent plots are nicer), + changed the modelbased plots to predictions and marginal means, which are arguably the most useful and appealing ones (we can showcase the contrasts plots in a subsequent paper with the lighthouse plots and all that).

**Comment by bwiernik** [comment]
@DominiqueMakowski Should it be `estimate_contrasts()` rather than means?

**Comment by DominiqueMakowski** [comment]
I think we can save estimate_contrasts for a later piece, because the plot can still be improved and it's a non-traditional visualisation that we propose so it would require a bit more explanation as to what the plot shows, and this paper is not really the place to do that

**Comment by bwiernik** [comment]
> The package provides also color palettes, such as `scale_color_material` or `scale_color_flat` for material and flat design colors, respectively.

Do we have citations for material and flat sources?

**Comment by DominiqueMakowski** [comment]
It's taken from these palettes: https://www.materialui.co/colors (different palettes under the upper left dropdown)

**Comment by IndrajeetPatil** [comment]
I have added the URL for palettes.

@strengejacke I will leave it up to you to decide if you wish to write about _sjPlot_ and how it compares to _see_.

**Comment by IndrajeetPatil** [comment]
I have already checked if there are any compilation issues with whedon preview, and no compilation errors 👍

https://whedon.theoj.org/

**Comment by IndrajeetPatil** [comment]
Final checks for submission:
- [ ] Clear contributing guidelines on `README`
- [ ] Code of Conduct on `README`

**Comment by pdwaggoner** [comment]
Great work on spearheading this paper @IndrajeetPatil  - many thanks!

**Comment by strengejacke** [comment]
A statement of need is missing in the readme, and in our paper we focus on models / visualization of easystats packages, while example usage in the readme focuses on geoms. We need to add further examples, or clarify / discuss the differences in examples we show in the readme and the paper.

**Comment by IndrajeetPatil** [comment]
Working on that now. Will try to have the same content as in the paper to be consistent.

**Comment by IndrajeetPatil** [comment]
Okay, done. `README` now has an Intro, a Statement of Need, and example for individual packages with links to vignettes for additional examples.

@strengejacke In case you decide to submit the paper over the weekend, you will need to re-knit the paper because I think had an out-of-date version of `modelbased` and so the examples are not rendered. If not, I will do this on Monday on my Windows machine.

<img width="885" alt="Screenshot 2021-06-11 at 17 45 27" src="https://user-images.githubusercontent.com/11330453/121713276-f8293c80-cadc-11eb-843d-a4fb441d0537.png">

**Comment by bwiernik** [comment]
I can knit in the morning on Windows

**Comment by IndrajeetPatil** [comment]
Okay, fixed the `modelbased` issue.

@strengejacke This is ready for submission now!

**Comment by IndrajeetPatil** [comment]
Closing since, except submission, not much needs to be done here now.

**Comment by IndrajeetPatil** [comment]
@strengejacke A list of possible reviewers to mention in the issue upon submission:

- JohnCoene
- trinker
- garretrc
- MatthewSmith430
- cdcrabtree
- jakobbossek
- tweed1e

**Comment by strengejacke** [comment]
submitted. Will wait for reviewer suggestions to be open.

**Comment by IndrajeetPatil** [comment]
You can now track progress at: https://github.com/openjournals/joss-reviews/issues/3372

**Comment by IndrajeetPatil** [comment]
> Will wait for reviewer suggestions to be open.

@strengejacke It's open now!

**Comment by IndrajeetPatil** [comment]
Congrats, everyone! 🎉 

https://joss.theoj.org/papers/10.21105/joss.03393

**Comment by bwiernik** [comment]
Woohoo!

**Comment by pdwaggoner** [comment]
Well done all!
