### ISSUE TITLE
No title printed when doing plot(model_parameters(x), main="title"), at least in the case of a lavaan cfa object.

### ISSUE THREAD

**Issue by simonfelding** [easystats/see#111]
Dear easystats developers, thank you so much for your amazing work. It is SO useful!

Attached is a screenshot that shows the issue. It might just be me, but I really can't find a way to make `plot()` print the title. I tried with `plot(x) + title("title")` too, but it doesn't seem to do anything.

I hope I'm not being stupid here, but it seems like there's a default that somehow disables `title=` and `main=`, which are arguments one would expect to work with `plot()`.
`plot(x, title="title")` doesn't work either.

I seem to get a potentially useful error when using r markdown:
`Error in title("title") : plot.new has not been called yet
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> title
Execution halted`

<img width="1188" alt="Screenshot 2021-04-11 at 16 46 16" src="https://user-images.githubusercontent.com/45149055/114308900-ab79b300-9ae5-11eb-8409-1dd70b61c6c1.png">

**Comment by DominiqueMakowski** [comment]
The returned plot is essentially a ggplot object, so you can add a title as follows:

``` r
library(parameters)
library(see)

structure <- "
    # latent variable definitions
      ind60 =~ x1 + x2 + x3
      dem60 =~ y1 + y2 + y3 + y4
      dem65 =~ y5 + y6 + y7 + y8
    # regressions
      dem60 ~ ind60
      dem65 ~ ind60 + dem60
  "

model <- lavaan::sem(structure, data = lavaan::PoliticalDemocracy)
x <- parameters::model_parameters(model)

plot(x, layout = "fr") +
  ggplot2::ggtitle("My title")
```

![](https://i.imgur.com/2zUIPQh.png)

<sup>Created on 2021-04-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
