### ISSUE TITLE
pairwise contrasts visualisation: an idea (lighthouse plot)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#12]
# Context

Plotting pairwise contrasts is tricky because the "significance" of the contrasts is often quite poorly reflected by the CIs of the estimated means. 

Russ (from emmeans) suggested the [following](https://github.com/rvlenth/emmeans/issues/93):

> * The way SAS does it is to plot each pair of means in a 2D plot, along with the identity line and CIs (scaled by sqrt(1/2)) for the differences of the means going perpendicular to the identity line, centered at each point. A difference is statistically significant if the interval does not cross the identity line. I programmed that up, but I find it very hard to label the plot effectively and don't care much for it.
> * You can try `emmeans::plot(emm, comparisons = TRUE)` where `emm` is the result of an `emmeans()` call. This adds red arrows to the plot which indicate significant differences when the arrows don't overlap. This uses an _ad hoc_ algorithm, and it is not guaranteed to be possible, especially when the SEs of the differences vary widely. Feedback from users has not been all that enthusiastic, and I'm not sure I like it so much either, but to me, when it works, it's better than the SAS approach.
> * If you do `emmeans::CLD(emm)`, it adds a column to the summary of `emm` showing a compact letter display. Two means that share the same letter are significantly different. This works, but it is very black-and-white: with alpha = .05, _P_ values slightly above or below .05 make a difference, but there's no difference between a _P_ value of .051 and one of .987, or between .049 and .00001 [note that recently Russ decided not to support this method anymore]

Here's how emmeans is [currently](https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html) doing it:

![image](https://user-images.githubusercontent.com/8875533/56300142-f87d5580-6167-11e9-999c-2d1c422c7440.png)

> The blue bars are confidence intervals for the EMMs, and the red arrows are for the comparisons among them. If an arrow from one mean overlaps an arrow from another group, the difference is not significant, based on the adjust setting (which defaults to "tukey"). (Note: Don’t ever use confidence intervals for EMMs to perform comparisons; they can be very misleading.)

# Proposition

However, I am not entirely satisfied with these ways of representing contrasts, which I found quite unintuitive or complex. I feel like there is a gap in the available ways of representing estimated contrasts. As I am often using them, I tried to imagine different ways of representing the differences between factor levels. 

I currently have an idea in mind, but I can't even say if it's a good solution, as I have troubles making the plot I have in mind in the first place. Get ready for some paint 🎨 

The idea would be to represent at the same time means and intervals (via pointrange). Then, each pairwise contrast would be shown as a "ray of light" (a triangle basically) starting from the lefthand level, and spanning over the CI of the difference + the mean of the left level. 

For the contrast between levels A and B, there would be a triangle with one corner located at the mean of A, and it would "project" over the interval of the CI *of the difference* at B.

![image](https://user-images.githubusercontent.com/8875533/56301089-afc69c00-6169-11e9-90b2-addc5b41c20b.png)

In dark red are the estimated means and their CIs and in light green would be the CI_high and CI_low of the difference (added to the mean of A). The dark green line would be the "mean" difference. 

This could be interpreted as: for one this given value of A, B would be in the green area. I.e., independently of the variability of the means, B would be always (in this case) bigger than A.

For multiple levels, I have the means:

``` r
library(tidyverse)
library(rstanarm)
library(estimate)
library(see)

model <- stan_glm(Sepal.Width ~ Species, data=iris)
contrasts <- estimate_contrasts(model)
means <- estimate_means(model)

means %>%
  ggplot() +
  geom_pointrange(data=means, aes(x=Species, y=Median, ymin=CI_low, ymax=CI_high))
```

![](https://i.imgur.com/IA70UId.png)

<sup>Created on 2019-04-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

But then I have no clear idea how to approach something like this:

![image](https://user-images.githubusercontent.com/8875533/56301862-447dc980-616b-11e9-9ced-b6e010c94da8.png)

(values are arbitrary)

I don't if the best way to achieve this is through geom_polygon or geom_ribbon.

Does this idea makes any sense?

**Comment by strengejacke** [comment]
I started with some drafts for ggeffects, but couldn't come up with a satisfactory solution, either.

**Comment by DominiqueMakowski** [comment]
This code chunk manages to approach the end result, but I am not sure how...

Although there are still some things wrong, e.g. the middle-level (`versicolor`) should be the "lowest", whereas in that plot it is `virginica` that appears as the lowest...

``` r
library(tidyverse)

contrasts <- data.frame(Level1 = c("setosa", "setosa", "versicolor"),
                        Level2 = c("versicolor", "virginica", "virginica"),
                        Diff = c(0.65, 0.46, -0.20),
                        CI_low = c(0.53, 0.35, -0.32),
                        CI_high = c(0.75, 0.56, -0.09))

means <- data.frame(Species = c("setosa", "versicolor", "virginica"),
                    Mean = c(3.42, .77, 2.97))

contrasts %>% 
  bind_cols(id=1:3) %>% 
  inner_join(means, by=c('Level1' = 'Species')) %>% 
  select(id, x=Level1, y=Mean) %>% 
  bind_rows( (contrasts %>% 
                bind_cols(id=1:3) %>% 
                select(id, x=Level2, y=CI_low)),
             (contrasts %>% 
                bind_cols(id=1:3) %>% 
                select(id, x=Level2, y=CI_high))) %>% 
  ggplot(aes(x = x, y= y, group=id)) + 
  geom_polygon()
```

![](https://i.imgur.com/v0olj9K.png)

<sup>Created on 2019-04-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
I'm not sure whether we're on the optimal track for this visualizaton. I'm not sure, but when I look at what we're trying to do here, maybe the circlize-package has some function we could use?

I could imagine visualizing it tis way:
https://jokergoo.github.io/circlize_book/book/the-chorddiagram-function.html

**Comment by DominiqueMakowski** [comment]
I've made a first draft for the "lighthouse" plot (see [here](https://github.com/easystats/see#pairwise-contrasts)). Must be further tested and all.

Couldn't manage to easily add the "median" or mean difference yet. But having the CIs is already something.

**Comment by pdwaggoner** [comment]
That's pretty slick looking; well done.

**Comment by bwiernik** [comment]
@DominiqueMakowski Late to the party, but I think the current implementation works well with just the CI. The mean points themselves already visualize mean difference by showing the distance between them. 

One really nice thing about this display it that it will nicely work with repeated measures/dependent groups designs, where the CI on the difference will be smaller than the CIs on the means themselves. Visualizing these models is always super tricky. Most papers just plot the means and their CIs, which overstates the uncertainty. The most common plot that does accurately reflect the uncertainty is a pairwise comparison bar chart, but this then doesn't convey the means themselves. The lighthouse plot is a really elegant solution here. 

I think there would be value in publishing a short paper (e.g., maybe in Behavioral Research Methods?) on visualizing within-group designs with examples of different approaches and their pros/cons, highlighting lighthouse plots and perhaps spaghetti plots as having the best statistical fidelity.

**Comment by DominiqueMakowski** [comment]
I'm so happy that you like the lighthouse plots 🙌  I do think that they are a new and viable solution to an old, pesky and common problem and that it would be worth expanding on that, through paper, posts and what not.

The problem is that I'm not 100% sure the current implementation is really robust, and it would benefit to be looked at and somewhat test a bit further. Maybe we should create a new geom? like `geom_lightbeam` or something? To facilitate the creation of such plots? 

I wonder how it could coexist with other aesthetics like color, fill etc.

**Comment by IndrajeetPatil** [comment]
> I think there would be value in publishing a short paper (e.g., maybe in Behavioral Research Methods?) 

Wholeheartedly agree with this! Will be a very valuable guide for users to understand this visualization method.
