### ISSUE TITLE
adding subtitle to `plot.check_homogeneity` to clarify what should be the case?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#146]
Should we add a subtitle here to clarify what should be the case?

![image](https://user-images.githubusercontent.com/11330453/121770996-0c1c7f00-cb6d-11eb-8102-a30a9b2f6daf.png)

This will bring this visualization in line with output from other `check_` functions, whose subtitles make it clear what _should be_ the case:

![image](https://user-images.githubusercontent.com/11330453/121770968-ceb7f180-cb6c-11eb-9895-a49efb6280a6.png)

**Comment by bwiernik** [comment]
Is the y-axis here the DV? If so, perhaps we should group-mean center the violins so that we can say "density curves should be similar in shape"?

Would this plot be easier if they were plotted as a ridge plot?

**Comment by bwiernik** [comment]
Looking at this plot, I'm not actually sure what it's showing. Why are there 10 violins instead of 6?

Shouldn't this:
```r
  p <- if (length(pred) > 1) {
    ggplot(data = dat, aes(x = .data$x, y = .data$y, fill = .data$group)) +
      geom_violin()
  } else {
    ggplot(data = dat, aes(x = .data$x, y = .data$y)) +
      geom_violin(fill = "#2980b9")
  }
```

be:
```r
  p <- if (length(pred) > 1) {
    ggplot(data = dat, aes(x = .data$group, y = .data$y, fill = .data$group)) +
      geom_violin()
  } else {
    ggplot(data = dat, aes(x = .data$x, y = .data$y)) +
      geom_violin(fill = "#2980b9")
  }
```

![image](https://user-images.githubusercontent.com/4773225/121911579-e2df2880-ccfd-11eb-8ce6-491c7ab0fc9e.png)

**Comment by IndrajeetPatil** [comment]
You are right! Here is another example:

``` r
library(performance)
library(palmerpenguins)
model <<- lm(body_mass_g ~ sex + species, data = penguins)
plot(check_homogeneity(model))
#> OK: Variances in each of the groups are the same (Bartlett Test, p = 0.174).
```

![](https://i.imgur.com/EBEGAiY.png)

<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
@bwiernik One thing: Can we have the group labels either in legend or as x-axis labels?

Reprex with PR:

``` r
library(performance)
library(palmerpenguins)
model <<- lm(body_mass_g ~ sex + species, data = penguins)
plot(check_homogeneity(model))
#> OK: Variances in each of the groups are the same (Bartlett Test, p = 0.174).
```

![](https://i.imgur.com/cW0u02r.png)

<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
How about:
![image](https://user-images.githubusercontent.com/4773225/121920312-ea0a3480-cd05-11eb-8913-701266ae37b9.png)

**Comment by bwiernik** [comment]
![image](https://user-images.githubusercontent.com/4773225/121923290-c5fc2280-cd08-11eb-956e-4e262a641ae1.png)

**Comment by IndrajeetPatil** [comment]
Awesome! 

The labels work well even with weird distributions:

``` r
library(performance)
library(palmerpenguins)
model <<- lm(brainwt ~ vore, data = ggplot2::msleep)
plot(check_homogeneity(model))
#> Warning: Variances differ between groups (Bartlett Test, p = 0.000).
```

![](https://i.imgur.com/RA5TptY.png)

<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
