### ISSUE TITLE
CRAN or too soon?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#15]
Even though this is currently a relatively small and preliminary package, maybe we could think about releasing it on CRAN. Thus, we could start using it in vignettes etc. What do you think?

**Comment by strengejacke** [comment]
yes, there are already some useful functions... but I would revise the equivalence-plot, putting the red shaded rectangle behind the density-curves. I coudln't find that function in the code, though.

**Comment by strengejacke** [comment]
Just saw, it's the rope plot... ^^

**Comment by DominiqueMakowski** [comment]
Yes... didn't want to overwrite your implementation in bayestestR 😉 

...Although I thought about having something similar to the ROPE plot (shades for different levels of CIs), but with different tones depending on the equivalence test outcome (red, yellow and green as in your version). Unfortunately, I didn't manage to have at the same time different shades in the same ridges and different general tones between ridges...

**Comment by strengejacke** [comment]
I just saw from `?plot.rope`:

```r
## S3 method for class 'estimateContrasts'
data_plot(x, data = NULL, ...)

## S3 method for class 'estimateContrasts'
plot(x, data = NULL, ...)

## S3 method for class 'hdi'
data_plot(x, data = NULL, ...)

## S3 method for class 'hdi'
plot(x, data = NULL, ...)

## S3 method for class 'p_direction'
data_plot(x, data = NULL, ...)

## S3 method for class 'p_direction'
plot(x, data = NULL, ...)

## S3 method for class 'rope'
data_plot(x, data = NULL, ...)
```

I think we can remove the `@rdname` tags, so we don't have the same function calls for each class, and then probably integrate the examples in the `data_plot.R` file, also removing some examples? I don't think we need example for each function/class...

**Comment by strengejacke** [comment]
Shall we do a radical step and move the implementation in bayestestR to see? And then releasing bayestestR and see shortly after each other, hoping that users won't miss the plot-method for a few days?

**Comment by DominiqueMakowski** [comment]
> Shall we do a radical step and move the implementation in bayestestR to see?

Yes, although maybe with some adjustments? Because from what I recall the current implementation plots the density estimations of the data in the CIs, which can give distorted results for instance when CI = 0.5 or something (can't confirm as I currently experience problems with equi test for models, not sure why).

On an implementation and dependency side, one of the initial proposals was to reexport in all of the packages the relevant plot methods for their objects. This was assuming that the `see` package would never be loaded alone. However, now that it includes some other stuff (themes, geoms etc.), people might want to use it, in which case it would create conflicts with the reexports. At the same time, leaving the plot methods here only would make them hard to be discovered from the other packages.

Thus, an (ugly) compromise would be to implement here full methods, named `plot_hdi`, `plot_rope`, `plot_equivalence_test` etc. And, in the other packages, example in baysetestR, the plot method for the objects would have the classic `if(!require('see')) error("please download 'see'")`. Thus, no additional dependencies with the raw bayestestR, but plot methods exist and guide the user.

The only problem with this could be the proliferation, with the loading of `see`, of `plot_*` functions. Maybe we could have them as internals, and use the internals in the other packages... But that could be an issue for CRAN?

**Comment by strengejacke** [comment]
we could add two class-attributes to every object (like adding a `rope_bayestestr` as first class-attribute or so), then have a `plot.rope_bayestestr()` method that requires see, and if successful, uses `NextMethod()`. That again should call the plot() from see.

**Comment by strengejacke** [comment]
Are there any urgent things remaining before we try to submit to CRAN?

- [ ] DESCRIPTION file
- [ ] ...

**Comment by pdwaggoner** [comment]
Just reviewed the package and I think everything looks pretty good for a first shot to CRAN. Definitely solid functionality to help a bunch of researchers out there. There are things that we can/should add, but at the moment, it feels ready to me to submit to CRAN. 

This could be for a future iteration for sure, but I just released a new package that is a color palette generator for palettes incorporating red, gray, blue, which are colors we frequently associate with American politics research (my original field, from which I am straying a bit these days...) It's called `amerika`: https://github.com/pdwaggoner/amerika and is flexible for discrete or continuous applications. We could add this to the palette options in the `see` package in the future if you're interested just to offer some more nuance for users. But we certainly don't have to! Just an idea.

**Comment by strengejacke** [comment]
I think blue/red color palettes are common and applicable in many contexts, so yes, why not adding this to _see_?

**Comment by DominiqueMakowski** [comment]
as a dep or as an integration?

**Comment by pdwaggoner** [comment]
So the way it seems to be now, there are palette options from the "material" colors. I was thinking to have this be another option to constrain colors for plots. So users could, in effect, select one of the material palette options or the `amerika` option, and then either continuous/gradient or discrete. Does this make sense with the current architecture? If not, its no big deal to pass on this. Or like I initially said, we could push the current stable version to CRAN and think about creatively tying in various palette options for future releases. Whatever makes most sense to you guys is just fine by me.

**Comment by strengejacke** [comment]
@DominiqueMakowski can you add some content to the docs of `add_plot_attributes()`? I'm not 100% sure what that method does. ;-)

**Comment by DominiqueMakowski** [comment]
Later today/tmr I will try to give `see` some love to polish it before release, including testing and documentation. FYI, `add_plot_attributes` is meant to retrieve and add stuff as plot title, axis titles etc.

**Comment by strengejacke** [comment]
@DominiqueMakowski I see this point: https://easystats.github.io/see/reference/add_plot_attributes.html still on the list.

Else, anything to add, or can we try to submit to CRAN?

**Comment by DominiqueMakowski** [comment]
I'll try adding this evening a method for plot_estimate and see if I can quickly implement de data_plot -> plot workflow to bayesfactor_models (it looks fairly easy). In any case, you can submit tomorrow ☺️

**Comment by strengejacke** [comment]
I'll submit next week, probably Monday or Truesday, if everything is ok.

**Comment by strengejacke** [comment]
@mattansb @DominiqueMakowski When I get your OK, I prepare the final steps for submission...

**Comment by DominiqueMakowski** [comment]
you got my green light 💚

**Comment by mattansb** [comment]
👌

**Comment by strengejacke** [comment]
Note this plot:

![image](https://user-images.githubusercontent.com/26301769/58012623-28b46d00-7af5-11e9-968f-25e85455f8d5.png)

I have changed the code so the legend is not shown when `stacked = FALSE`.

**Comment by DominiqueMakowski** [comment]
👍

**Comment by strengejacke** [comment]
Actually, we should remove the intercept by default...

``` r
library(bayestestR)
library(rstanarm)
#> Loading required package: Rcpp
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
#> Registered S3 method overwritten by 'xts':
#>   method     from
#>   as.zoo.xts zoo
#> rstanarm (Version 2.18.2, packaged: 2018-11-08 22:19:38 UTC)
#> - Do not expect the default priors to remain the same in future rstanarm versions.
#> Thus, R scripts should specify priors explicitly, even if they are just the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#> options(mc.cores = parallel::detectCores())
#> - Plotting theme set to bayesplot::theme_default().

model <- rstanarm::stan_glm(mpg ~ hp * gear, data = mtcars)
#> 
#> SAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).
#> Chain 1: 
#> Chain 1: Gradient evaluation took 0 seconds
#> Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
#> Chain 1: Adjust your expectations accordingly!
#> Chain 1: 
#> Chain 1: 
#> Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 1: 
#> Chain 1:  Elapsed Time: 0.228 seconds (Warm-up)
#> Chain 1:                0.246 seconds (Sampling)
#> Chain 1:                0.474 seconds (Total)
#> Chain 1: 
#> 
#> SAMPLING FOR MODEL 'continuous' NOW (CHAIN 2).
#> Chain 2: 
#> Chain 2: Gradient evaluation took 0 seconds
#> Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
#> Chain 2: Adjust your expectations accordingly!
#> Chain 2: 
#> Chain 2: 
#> Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 2: 
#> Chain 2:  Elapsed Time: 0.234 seconds (Warm-up)
#> Chain 2:                0.276 seconds (Sampling)
#> Chain 2:                0.51 seconds (Total)
#> Chain 2: 
#> 
#> SAMPLING FOR MODEL 'continuous' NOW (CHAIN 3).
#> Chain 3: 
#> Chain 3: Gradient evaluation took 0 seconds
#> Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
#> Chain 3: Adjust your expectations accordingly!
#> Chain 3: 
#> Chain 3: 
#> Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 3: 
#> Chain 3:  Elapsed Time: 0.239 seconds (Warm-up)
#> Chain 3:                0.209 seconds (Sampling)
#> Chain 3:                0.448 seconds (Total)
#> Chain 3: 
#> 
#> SAMPLING FOR MODEL 'continuous' NOW (CHAIN 4).
#> Chain 4: 
#> Chain 4: Gradient evaluation took 0 seconds
#> Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
#> Chain 4: Adjust your expectations accordingly!
#> Chain 4: 
#> Chain 4: 
#> Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 4: 
#> Chain 4:  Elapsed Time: 0.235 seconds (Warm-up)
#> Chain 4:                0.205 seconds (Sampling)
#> Chain 4:                0.44 seconds (Total)
#> Chain 4:

result <- estimate_density(model)

plot(result)
```

![](https://i.imgur.com/ViHSMEj.png)

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
like an argument, `remove_intercept`, or `show_intercept`?

**Comment by mattansb** [comment]
`show_intercept` with default to `FALSE`

**Comment by strengejacke** [comment]
exactly what I was thinking of!

**Comment by strengejacke** [comment]
haha, though in my example it's actually not the intercept that causes the strong peak ^^
But anyway, in two "real world examples", the intercept is often very different from the other parameters.

**Comment by DominiqueMakowski** [comment]
Yes. Maybe add an argument like "show_intercept" or simply "intercept". We could add this to other functions such as plot.pd, plot.hdi, plot.rope etc.

**Comment by strengejacke** [comment]
yes, that also came to my mind, and I just implemented it...

**Comment by strengejacke** [comment]
ok, wasn't supposed to close this, actually ;-) But I think it's really closed.
now undergoing win-builder tests and waiting for travis to confirm everything is ok, then I'll submit.

Webpage and readme updated with new plots.

**Comment by strengejacke** [comment]
>  Thanks,
> on its way to CRAN.
