### ISSUE TITLE
feature request: adding a plotting method for `check_overdispersion()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#153]
cf. https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html

<img width="850" alt="Screenshot 2021-06-16 at 20 13 53" src="https://user-images.githubusercontent.com/11330453/122271172-6dcb4900-cedf-11eb-9a74-0e9281db3d72.png">

**Comment by strengejacke** [comment]
We now have an overdispersion plot, I think this can be closed.

``` r
library(glmmTMB)
library(performance)
data(Salamanders)
m <- glm(count ~ spp + mined, family = poisson, data = Salamanders)
check_overdispersion(m) |> plot()
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/9KU35X1.png)

<sup>Created on 2022-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
(we also have a second style, both implemented from Brenton)

``` r
library(glmmTMB)
library(performance)
data(Salamanders)
m <- glm(count ~ spp + mined, family = poisson, data = Salamanders)
check_overdispersion(m) |> plot(type = 2)
```

![](https://i.imgur.com/bEyBjok.png)

<sup>Created on 2022-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
