### ISSUE TITLE
plotting method for `test_performance()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#154]
Should we have something similar to `compare_performance()`?  

That is, a radar chart with BF (and, if available, other) values.

**Comment by bwiernik** [comment]
Currently, `test_performance()` only returns one type of test, so I'm not sure a radar chart makes the most sense. Maybe instead some sort of stacked bar chart reflecting relative likelihood (e.g., AIC weights for test_aic() or test_lrt(), Bayes factor weights) or a bar chart for Wald or Vuong tests (though Vuong could also get something like 

In addition to the existing tests, `test_AIC()` and `test_R2()` and `test_R()` would be rgood additions. I also don't see a way to change the metric used in `test_performance()` (seems to always just give Bayes factors). Should it have a method argument?

**Comment by DominiqueMakowski** [comment]
> seems to always just give Bayes factors

🤔 test_performance gives more than just one test, assuming the models are appropriate:

``` r
m1 <- lm(Sepal.Length ~ Petal.Width, data = iris)
m2 <- lm(Sepal.Length ~ Petal.Width + Species, data = iris)
m3 <- lm(Sepal.Length ~ Petal.Width * Species, data = iris)

performance::test_performance(m1, m2, m3)
#> Name | Model |    BF |   Omega2 | p (Omega2) |   LR | p (LR)
#> ------------------------------------------------------------
#> m1   |    lm |       |          |            |      |       
#> m2   |    lm | 0.007 | 9.54e-04 |      0.935 | 0.15 |  0.919
#> m3   |    lm | 0.037 |     0.02 |      0.081 | 3.41 |  0.099
#> Models were detected as nested and are compared in sequential order.
```

<sup>Created on 2021-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

> test_AIC() and test_R2() and test_R() would be good additions

Absolutely!

> Plot for test_performance

Mmh I wonder what visualisation type would make sense. Let me think of it

**Comment by DominiqueMakowski** [comment]
As I see it, there are two components in the table that can be "hard" to read (or at least, not straightforward to "get"). That is, which model is compared to which, and what's the general conclusion (different or not).

So these are the areas where a visualisation could be useful. 


Right now, I could in my mind I see something like this, with direct links between 2 models compared showing 1) the conclusion (the color) and 2) the "weight" of the conclusion (the ratio of colors - since there's one for each test). One could also add on top of that aesthetics for which test (for instance using `linetype`, like dashed line for BF, dotted-line for LRT etc):

![ex2](https://user-images.githubusercontent.com/8875533/122314063-0ac2cc00-cf4a-11eb-9316-a537b3355754.png)

(note: colors are based on the two highlighters available within my reach)



But the general goal would be to have some plot that shows which models are sig. different "at first glance"

**Comment by bwiernik** [comment]
I think a simpler graph might be more informative. For example, plotting the relative likelihood weights as a stacked bar chart. Could even do stacks for each of the statistics if you wanted.

**Comment by DominiqueMakowski** [comment]
by "weight" I meant the amount of tests that conclude one thing or the other, not necessarily the associated statistics

**Comment by bwiernik** [comment]
I know what what you meant. What I am saying is that I think a stacked bar chart would convey the same idea more clearly.

**Comment by bwiernik** [comment]
> 🤔 test_performance gives more than just one test, assuming the models are appropriate:

``` r
library(performance)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
test_performance(lm1, lm2, lm3)
#> Name | Model |     BF
#> ---------------------
#> lm1  |    lm |       
#> lm2  |    lm | > 1000
#> lm3  |    lm |  0.038
#> Models were detected as nested and are compared in sequential order.
sessionInfo()
#> R version 4.1.0 (2021-05-18)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19043)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> system code page: 65001
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] performance_0.7.2
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.33        magrittr_2.0.1    insight_0.14.1.1  rlang_0.4.11     
#>  [5] fansi_0.5.0       stringr_1.4.0     styler_1.4.1      highr_0.8        
#>  [9] tools_4.1.0       xfun_0.21         utf8_1.2.1        bayestestR_0.10.5
#> [13] withr_2.4.2       htmltools_0.5.1.1 ellipsis_0.3.2    yaml_2.2.1       
#> [17] digest_0.6.27     tibble_3.1.2      lifecycle_1.0.0   crayon_1.4.1     
#> [21] purrr_0.3.4       vctrs_0.3.8       fs_1.5.0          glue_1.4.2       
#> [25] evaluate_0.14     rmarkdown_2.8.6   reprex_2.0.0      stringi_1.5.3    
#> [29] compiler_4.1.0    pillar_1.6.1      backports_1.2.1   pkgconfig_2.0.3
```

<sup>Created on 2021-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Strange, I see what Dom sees. Need to study session info to see why the different outputs.

``` r
library(performance)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
test_performance(lm1, lm2, lm3)
#> Name | Model |     BF | Omega2 | p (Omega2) |     LR | p (LR)
#> -------------------------------------------------------------
#> lm1  |    lm |        |        |            |        |       
#> lm2  |    lm | > 1000 |   0.69 |     < .001 | 127.22 | < .001
#> lm3  |    lm |  0.038 |   0.03 |     0.223  |   3.47 | 0.200 
#> Models were detected as nested and are compared in sequential order.
```

<sup>Created on 2021-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
Coud be recent update related to nested models detection (same response etc)

**Comment by DominiqueMakowski** [comment]
> a stacked bar chart would convey the same idea more clearly.

I don't picture it but feel free to give a try in code or paintbrush 🎨

**Comment by bwiernik** [comment]
eg,

``` r
library(ggplot2)
d <- data.frame(x = 1:20, y = rpois(20, lambda = 2))
m0 <- glm(y ~ 1, data = d)
m1 <- update(m0, . ~ x)
m2 <- update(m0, . ~poly(x, 2))
dplyr::full_join(
  tibble::rownames_to_column(
    as.data.frame(bbmle::ICtab(m0, m1, m2, weights = TRUE, type = "AIC")),
    "model"
  ),
  tibble::rownames_to_column(
    as.data.frame(bbmle::ICtab(m0, m1, m2, weights = TRUE, type = "BIC")),
    "model"
  ),
  by = "model", 
  suffix = c("_AIC", "_BIC")
) |> 
  dplyr::select(model, weight_AIC, weight_BIC) |> 
  tidyr::pivot_longer(
    cols = c(weight_AIC, weight_BIC),
    names_to = c(".value", "metric"),
    names_sep = "_"
  ) |> 
  ggplot() +
  aes(x = metric, y = weight, color = model, fill = model) +
  geom_col(position = "stack")
```

![](https://i.imgur.com/8nhrbbl.png)

<sup>Created on 2021-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
What I like about this is that it very clearly indicates the relative support for each model in the set.

**Comment by strengejacke** [comment]
Looks similar to what are have for Bayes factors: https://easystats.github.io/see/articles/bayestestR.html#bayes-factors-for-model-comparison

**Comment by IndrajeetPatil** [comment]
How about lollipop charts instead? Seems a bit cleaner to my eyes and also easier to make comparisons w.r.t. a horizontal scale.

``` r
library(ggplot2)
d <- data.frame(x = 1:20, y = rpois(20, lambda = 2))
m0 <- glm(y ~ 1, data = d)
m1 <- update(m0, . ~ x)
m2 <- update(m0, . ~poly(x, 2))

df <- 
  dplyr::full_join(
    tibble::rownames_to_column(
      as.data.frame(bbmle::ICtab(m0, m1, m2, weights = TRUE, type = "AIC")),
      "model"
    ),
    tibble::rownames_to_column(
      as.data.frame(bbmle::ICtab(m0, m1, m2, weights = TRUE, type = "BIC")),
      "model"
    ),
    by = "model", 
    suffix = c("_AIC", "_BIC")
  ) |> 
  dplyr::select(model, weight_AIC, weight_BIC) |> 
  tidyr::pivot_longer(
    cols = c(weight_AIC, weight_BIC),
    names_to = c(".value", "metric"),
    names_sep = "_"
  ) |> 
  dplyr::arrange(metric, -weight)

library(ggcharts)
lollipop_chart(df, model, weight, facet = metric,
               point_color = "darkgreen", line_color = "gray")
```

![](https://i.imgur.com/WSTBaNM.png)

<sup>Created on 2021-06-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
> Looks similar to what are have for Bayes factors:

I definitely prefer a labelled pie chart over an unlabelled bar chart! 🙈

**Comment by strengejacke** [comment]
why plots at all?

**Comment by bwiernik** [comment]
> an unlabelled bar chart! 

Didn't spend any time making the chart pretty 😜

@strengejacke In fact, it looks like the default "bayes factors" that are being computed here are just the BIC weights.

**Comment by DominiqueMakowski** [comment]
I'm not convinced by this plot which doesn't reflect the table-output of `test_performance`. Essentially, this set of functions is about making binary conclusions, i.e., whether models are different or not. The underlying index used to reach that conclusion is secondary here (contrary to, for instance, `compare_performance`, which provides a set of performance metrics and leaving the interpretation to the user). The important information in the output of `test_performance` is IMO what test gives what conclusion, which is not reflected in the above plot (which is more reflective of what I could expect from `plot(compare_performance)`)

**Comment by bwiernik** [comment]
I don't really see the value of a plot for test_* then

**Comment by strengejacke** [comment]
As I wrote...

> why plots at all?

**Comment by IndrajeetPatil** [comment]
_Mea culpa_ 

Just wanted to brainstorm if we could think of something that would work here.

**Comment by DominiqueMakowski** [comment]
> As I see it, there are two components in the table that can be "hard" to read (or at least, not straightforward to "get"). That is, which model is compared to which, and what's the general conclusion (different or not; across the different tests).

A plot could help with that above. I'll try to make a draft plot when I have time, but let's leave that open for now; I think in the long-run most of easystats objects should have some form of plotting methods (+ a report method - but that's even longer goal ^^)

**Comment by bwiernik** [comment]
I think I disagree with your characterization of what test is doing though. For all of these, they are continuous levels of evidence. AIC/BIC/BF are all relative out of sample likelihood indices--the correct conclusion from them might be "these two are better than that one, but neither is better than the other". I think a plot should reflect that

**Comment by strengejacke** [comment]
Is this issue still relevant? We have a radar chart for `compare_performance()`, which includes ICs.

**Comment by DominiqueMakowski** [comment]
Yeah I think for now it's enough. We can perhaps add a plot method that throws an error with `Please use plot(compare_performance(...))` to obtain a visual representation` or something like that to guide users. 

If someday we find suitable and relevant specific plots for specific tests we can always add them
