### ISSUE TITLE
pizza (and other BF) plots

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#16]
In bayestestR I mentioned [Wagenmakers' pizza analogy](https://www.bayesianspectacles.org/lets-poke-a-pizza-a-new-cartoon-to-explain-the-strength-of-evidence-in-a-bayes-factor/) for the BFs. 

It's not a secret that my favourite dish is pizza.  

I thought there a package for everything in R. Thus I looked for some pizza themes for pie charts...

*didn't find one*

Then I thought, this is something for `see`!

@mattansb what do you say about plot methods for the BFs objects that would return pizza pies (pie charts with a `theme_pizza`)?? Wouldn't that be the coolest thing *in the world*?

**Comment by mattansb** [comment]
🤣🤣🤣🤣
That's awesome!

I think it also might be good for sdBF to have comparative density plots (priors vs posteriors). Would this require priors and posteriors to be added as attributes to the sdBF object?

**Comment by DominiqueMakowski** [comment]
> I think it also might be good for sdBF to have comparative density plots (priors vs posteriors). Would this require priors and posteriors to be added as attributes to the sdBF object?

I think so yes. Currently, we store additional info required for plotting as attributes (example can be found in equivalence_test or rope). For the prior, maybe it would suffice to get the prior parameters and reconstruct the distribution?

**Comment by strengejacke** [comment]
I'm not sure how this could look like? Would you create multple "pizzas" for this one:

```r
lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1)
```

?

**Comment by DominiqueMakowski** [comment]
I would say so yes, a facetted plot with one pizza per bf.

now that I think of it, the most obvious would be to make redish circles with bf being a portion

**Comment by DominiqueMakowski** [comment]
I have a better plan for the look of it, but I need to check if it's possible to integrate images as fill.

we could render an actual image of pizza, and remove the slice corresponding to the bf. the bf would be the odds of not having pizza

**Comment by strengejacke** [comment]
> a facetted plot with one pizza per bf

uargh! ;-)

Better a forest plot... You don't really get the numbers / proportions for a _facetted pie chart_ plot, and you can't compare it w/o looking at that plot for hours... 

Believe me, I'm teaching data visualization and the appropriateness of plots! 🥇  ;-)

**Comment by DominiqueMakowski** [comment]
if this method of plotting bfs works I could actually start using bfs 😅😅

**Comment by DominiqueMakowski** [comment]
@strengejacke you are absolutely right about the non appropriateness of pie charts in general. Couldn't agree more... but you know here in Asia there's no chance of finding a proper pizza... please let me at least have a pizza chart... 😇

**Comment by mattansb** [comment]
These pizza plots represent the relative posterior probability of each model. So you have two options:

1. One pie with each model representing a slice.
2. One pie for each model vs the denominator model (but then you lose the visual comparison between the pies)

**Comment by strengejacke** [comment]
> please let me at least have a pizza chart...

Maybe we could add a "style" or "type" option to choose between different plot-styles. :-)

**Comment by DominiqueMakowski** [comment]
we could have the default "serious" and useful plot method. and then a separate function (`pizza(bf)`) that renders these marvels

**Comment by pdwaggoner** [comment]
I don't want to bias things here, but in my humble opinion, a buddy of mine (Bert Kim) captures my preferences with regard to pie (and pizza) charts -- see Figure 3.28 from his book here: https://moderndive.com/3-viz.html

All joking aside, this sounds like a cool option to offer in the package.

**Comment by DominiqueMakowski** [comment]
you are biased because you never ate a proper napolitean pizza (or maybe I am because I didn't makan yet (singaporean for eating)). next time we do a easymeeting in Paris I'll bring you guys to some of my favorite places 😋

**Comment by pdwaggoner** [comment]
Well said and you are right; I would be more than willing to walk my bias back after trying one of those. So its official then, we are meeting next in Paris?

**Comment by DominiqueMakowski** [comment]
I think only a visiting assistant professor has enough status to organise such event... so maybe the US? 😇

**Comment by pdwaggoner** [comment]
I'll see what I can do... ;)

**Comment by DominiqueMakowski** [comment]
https://cran.r-project.org/web/packages/patternplot/vignettes/patternplot-intro.html

![image](https://user-images.githubusercontent.com/8875533/57706090-a90f4400-7697-11e9-912d-f9d8b27cd2e2.png)

People have implemented this. Doesn't [seem too complicated](https://github.com/cran/patternplot/blob/master/R/patternpie.R#L35). All we have is too plot the round image of the pizza, compute and add a white (missing) "slice" 🍕

**Comment by mattansb** [comment]
This is what I have so far (on the second option I can't seem to get the text in the right place).
@DominiqueMakowski do you think this could work with `patternplot`?


``` r
library(bayestestR)
lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
BFs <- bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1)
BFs$BF <- c(1,3,4,5)
BFs
#> Bayes factor analysis
#> --------------                               
#> [2] Species                   3
#> [3] Species + Petal.Length    4
#> [4] Species * Petal.Length    5
#> 
#> Against denominator:
#>   [1] (Intercept only)   
#> ---
#> Bayes factor type:  BIC approximation

library(ggplot2)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
plot_data <- as.data.frame(BFs)
plot_data <- within(plot_data,{
  Model <- factor(Model, levels = Model)
  PostProb <- BF / sum(BF)
  pos <- sum(PostProb) + PostProb / 2 - cumsum(PostProb)
})

ggplot(plot_data, aes(x = "", y = PostProb, fill = Model)) +
  geom_bar(width = 1, stat = "identity") +
  # geom_text(aes(y = pos, label = BF)) +
  geom_text(aes(y = pos, label = scales::percent(PostProb,1))) +
  coord_polar("y", start = 0)
```

![](https://i.imgur.com/yooYVhe.png)

``` r


denominator <- attr(BFs,"denominator")
plot_data_f <- rbind(within(plot_data,Type <- Model),
                     within(plot_data,{
                       Type <- Model[denominator]
                       BF <- BF[denominator]
                       PostProb <- PostProb[denominator]
                     }))
plot_data_f <- within(plot_data_f,{
  PostProb <- sapply(split(PostProb,Model), function(x) x/sum(x))
  PostProb <- c(PostProb[1,],
                PostProb[2,])

  pos <- sapply(split(PostProb,Model), function(x) sum(x) + x / 2 - cumsum(x))
  pos <- c(pos[1,],pos[2,])
  Type <- as.character(Type)
  Model <- as.character(Model)
})
plot_data_f <- plot_data_f[plot_data_f$Model != BFs$Model[denominator],]

ggplot(plot_data_f, aes(x = "", y = PostProb, fill = Type)) +
  geom_bar(width = 1, stat = "identity") +
  # geom_text(aes(y = pos, label = BF)) +
  geom_text(aes(y = pos, label = scales::percent(PostProb,1))) +
  coord_polar("y", start = 0) +
  facet_wrap(~Model)
```

![](https://i.imgur.com/wIikotI.png)

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
This is super cool, great work!

I think it is a two-step process, first to implement the transformation from our BF objects to data ready to be plotted (e.g. with the `dataplot` function), which is what you already pretty much have done. Then the addition of a pizza skin is purely cosmetic and anecdotic ^^ Will look into when I'm hungry again

**Comment by mattansb** [comment]
I encourage you to take it from here - as you seem to be starved for any pizza-related activities (:

**Comment by strengejacke** [comment]
`theme_pizza()` doesn't work, what is it supposed to do?

**Comment by DominiqueMakowski** [comment]
I'll remove it (it was supposed to be a minimal theme with the pizza palette, but it doesn't work). I'll check about a general "image as fill" when I have time, for now we can live with regular pies :)

**Comment by mattansb** [comment]
Alright, all the basics are done :)

``` r
library(bayestestR)
library(see)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang

lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

mBF <- bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 1)
mBF$BF <- c(3,1,4,5) # so we can actually see anything
mBF
#> Bayes factor analysis
#> --------------                               
#> [2] Species                   1
#> [3] Species + Petal.Length    4
#> [4] Species * Petal.Length    5
#> 
#> Against denominator:
#>   [1] (Intercept only)   
#> ---
#> Bayes factor type:  BIC approximation

plot(mBF, n_pies = "one", value = "BF")
```

![](https://i.imgur.com/AxbUgwu.png)

``` r

plot(mBF, n_pies = "many", value = "Prob")
```

![](https://i.imgur.com/O7Bw3Pf.png)

<sup>Created on 2019-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
Closing this in favour of more specialised issues, as the core idea of this one have been addressed thanks to @mattansb (which makes me think, free free to add yourself in the package description). 

I have taken a look at the package that does piecharts with images as a fill, but it relies on some obscure C code. Unfortunately, I have not found any other pure R way of filling a geom with an image (which was unexpected). So the true pizza plots won't be for now 😞😢

**Comment by mattansb** [comment]
@DominiqueMakowski for your pleasure. (Where's the cheese?)
``` r
library(bayestestR)
library(see)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang

lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
mBF <- bayesfactor_models(lm1, lm2, lm3, lm4, denominator = 2)
mBF$BF <- c(1/3,1,3,4)

plot(mBF) +
  scale_fill_pizza_d()
```

![](https://i.imgur.com/GNUZlH8.png)

<sup>Created on 2019-05-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by strengejacke** [comment]
![image](https://user-images.githubusercontent.com/26301769/57920259-ebed3980-789a-11e9-9204-52d2b4fb93c7.png)

null-point geom with theme-specific (background-color) outline... :-)

**Comment by strengejacke** [comment]
![image](https://user-images.githubusercontent.com/26301769/57920356-20f98c00-789b-11e9-8925-5314cfed9851.png)

**Comment by strengejacke** [comment]
I updated the readme.

**Comment by mattansb** [comment]
Very cool!

**Comment by DominiqueMakowski** [comment]
I must say, the current figures for equi test and BFs in the README look gorgeous. Great job guys!

**Comment by mattansb** [comment]
@DominiqueMakowski have you seen [this](https://www.bayesianspectacles.org/lets-poke-a-pizza-a-new-cartoon-to-explain-the-strength-of-evidence-in-a-bayes-factor/):
![](https://i1.wp.com/www.bayesianspectacles.org/wp-content/uploads/2018/07/LetsPokeAPizza.jpg?w=2000&ssl=1)

**Comment by strengejacke** [comment]
haha, we could put this in the 'Details' section ;-)

**Comment by DominiqueMakowski** [comment]
@mattansb Yes this is the link I mentioned in the opening of the issue, this is where this whole idea comes from ^^ That's why it would be super funny to literally include it. I am sure Wagenmaker would like it. Unfortunately, it seems complicated to include images as fill in geoms 😢

**Comment by mattansb** [comment]
> Yes this is the link I mentioned in the opening of this issue
Oh yeah! I missed that!

I am still hopeful that we could add pictures in the future - don't lose hope!

**Comment by DominiqueMakowski** [comment]
@cratlagh showed me this implementation that I somehow missed: 

https://github.com/clauswilke/ggtextures 

That could be relevant for the pizza plot

**Comment by mattansb** [comment]
😒
```R
library(ggplot2)
library(ggtextures)

one_pie_data <- data.frame(
  PostProb = c(0.3,0.4,0.2,0.1),
  img = c(
    "http://www.hypergridbusiness.com/wp-content/uploads/2012/12/rocks2-256.jpg",
    "http://www.hypergridbusiness.com/wp-content/uploads/2012/12/stone2-256.jpg",
    "http://www.hypergridbusiness.com/wp-content/uploads/2012/12/siding1-256.jpg",
    "http://www.hypergridbusiness.com/wp-content/uploads/2012/12/rocks2-256.jpg"
  )
)

ggplot(one_pie_data, aes(x = "", y = .data$PostProb, image = .data$img)) +
  geom_textured_col(width = 1, stat = "identity", color = "white", size = .5) + 
  coord_polar("y", start = 0)
#> Warning message:
#> geom_textured_rect() does not work with nonlinear coords
```

**Comment by strengejacke** [comment]
We can hard-code it, and have a pizza-image for every possible proportions. :-D

**Comment by mattansb** [comment]
Sure! We can do some:
`see::geom_textured_arc_bar` =
`ggtextures::geom_textured_col` + [`ggforce::geom_arc_bar`](https://ggforce.data-imaginist.com/reference/geom_arc_bar.html)
