### ISSUE TITLE
`check_model()` doesn't return plots anymore

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#163]
Do you know why there is no plot output here anymore?

https://easystats.github.io/see/articles/performance.html#overall-model-check-1

Reprex shows the same thing:

``` r
library(performance)
m <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)

check_model(m)
```

<sup>Created on 2021-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

_Originally posted by @IndrajeetPatil in https://github.com/easystats/see/issues/160#issuecomment-870917388_

**Comment by IndrajeetPatil** [comment]
If I explicitly call `plot`, that doesn't work either.

``` r
library(performance)
m <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)

plot(check_model(m))
#> Error in xy.coords(x, y, xlabel, ylabel, log): 'x' is a list, but does not have components 'x' and 'y'
```

<sup>Created on 2021-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
Running dev versions of both performance and see?

**Comment by IndrajeetPatil** [comment]
I get output if I explicitly call `plot()`.

<img width="874" alt="Screenshot 2021-07-01 at 09 11 01" src="https://user-images.githubusercontent.com/11330453/124081842-4ed6c600-da4c-11eb-8946-c8dc7ac5a519.png">

But no output otherwise:

<img width="602" alt="Screenshot 2021-07-01 at 09 13 53" src="https://user-images.githubusercontent.com/11330453/124082170-ad03a900-da4c-11eb-83fe-2a1c140f2b11.png">

Note that this is a breaking change, since all users are currently using the function without explicitly calling `plot()`.

We should avoid this since this is probably the [most used function](https://twitter.com/patilindrajeets/status/1372078952517410820?s=20) in the ecosystem, and we need to make sure that its behavior doesn't change.

**Comment by bwiernik** [comment]
That was definitely not the intention and wasn't what I was observing before. Will check.
