### ISSUE TITLE
theme_solarized()

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#17]
Something like `ggthemes::theme_solarized(light = FALSE)`, but with a more contrastful color for axis labels, and maybe more beatiful legend?

Here's the ggthemes-theme:

``` r
library(easystats)
model <- rstanarm::stan_glm(mpg ~ wt + gear + cyl + disp, data = mtcars)
result <- equivalence_test(model)

plot(result) + ggthemes::theme_solarized(light = F) + scale_fill_material()
```

![](https://i.imgur.com/6e5Rvdg.png)

<sup>Created on 2019-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

@DominiqueMakowski what would you say? Can you quickly copy/re-use the code from the dark-theme?

**Comment by DominiqueMakowski** [comment]
I am not sure to understand, you would want a new theme, something like `theme_blackboard` (i.e., a mix of theme_modern + a dark background but with a "more contrastful color for axis labels, and maybe more beatiful legend"? Such as in the example?

**Comment by strengejacke** [comment]
Yes, `theme_blackboard()` has a black background, no grid. `theme_solarized()` has a (very) dark blue blackground, and grids. You could use the theme from ggthemr, but I don't like the too dark axis labels and the border around the legend that much, that's why I thought of a slightly "improved" theme_solarized() for _see_.

**Comment by strengejacke** [comment]
> Or maybe you'd like to reproduce the blue-ish glow of solarized?

Yeah, as alternative (not replacement) of theme_blackboard.

**Comment by DominiqueMakowski** [comment]
okay, I'll do it tomorrow. Any suggestions for a name? 

`theme_space`? `theme_galaxy` (people are gonna think we're sponsored by samsung) `theme_darkblueish` `theme_abyss` ...

**Comment by DominiqueMakowski** [comment]
`theme_abyss`: what do you think?

![image](https://user-images.githubusercontent.com/8875533/57896572-ee906480-7883-11e9-8660-f14ef7173730.png)

**Comment by strengejacke** [comment]
yes, looks good! I think such a slight nuance in the darkness, and gridlines, is a good alternative to the darktheme.
