### ISSUE TITLE
include more `modelbased` examples in the respective vignette

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#174]

**Comment by DominiqueMakowski** [comment]
This can wait for modelbased 0.9 as I think I can simplify a bit the API... it's currently WIP

**Comment by IndrajeetPatil** [comment]
Yepp, no hurry. I just wanted to make a note for ourselves, lest we forget.

**Comment by strengejacke** [comment]
_bump_

**Comment by IndrajeetPatil** [comment]
*bump bump*

**Comment by strengejacke** [comment]
_bump bump bump_

**Comment by DominiqueMakowski** [comment]
we could probably by copying straight up some examples from the different visualisation_recipe methods ([example](https://github.com/easystats/modelbased/blob/bddc27c7262dcf7ea8205c9813dad42393d07748/R/visualisation_recipe.estimate_means.R#L3-L47))

**Comment by strengejacke** [comment]
<sup><i>bump bump bump bump</i></sup>
