### ISSUE TITLE
BF pies - default aesthetics

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#18]
Minor, but what do you think of a white (instead of black) default colour (i.e., contour) for the pies? 😁

**Comment by mattansb** [comment]
Feel free to change the aesthetic in anyway you see fit to make it nicer /
more concise with the rest of `see` :)

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab
