### ISSUE TITLE
remove `.reshape_to_long`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#185]
Use [`datawizard::reshape_longer`](https://easystats.github.io/datawizard/reference/data_to_long.html) and remove the internal variant?

https://github.com/easystats/see/blob/ec14dc8fbf63950848d520ea9694fd62bcd08804/R/reshape_to_long.R

**Comment by strengejacke** [comment]
The internal variant coerces factors of reshaped columns into character - there must be a reason for this. To reproduce the same behaviour, we would end up having a similar long helper-function. I'm not sure we should do this?

**Comment by strengejacke** [comment]
> but without the original ordering?

I think exactly that's the point.
