### ISSUE TITLE
changing `size_text` returns empty visualisation for `parameters`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#187]
Strange that specifying the size of text labels removes estimates.

``` r
library(parameters)
library(glmmTMB)

mod <- glmmTMB(
  count ~ spp + mined + (1 | site),
  ziformula =  ~mined,
  family = poisson(),
  data = Salamanders
)

result <- parameters(mod)

plot(result, size_text = 4)
#> Warning in min(new_range): no non-missing arguments to min; returning Inf
#> Warning in max(new_range): no non-missing arguments to max; returning -Inf
#> Warning: Removed 2 rows containing missing values (geom_segment).
#> Warning: Removed 1 rows containing missing values (geom_segment).
```

![](https://i.imgur.com/9MofTHm.png)

<sup>Created on 2021-07-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Partly related to https://github.com/easystats/see/commit/fe39746eda4e6574f041f7862ca653eed15054a1.
Are there any other occurences with text values? See the minor change in my commit from `mapping = aes(label = .data$Estimate_CI, y = Inf)` to `mapping = aes(label = .data$Estimate_CI, x = Inf)` (tagging @bwiernik)

**Comment by bwiernik** [comment]
@strengejacke Is that right? This was a plot that previously had coord_flip() I believe.
