### ISSUE TITLE
forest plot for brms object no longer seems to work ...

### ISSUE THREAD

**Issue by MilaniC** [easystats/see#197]
library(brms)
model <- insight::download_model("brms_meta_1")
result <- model_parameters(model)

result
plot(result)

Error in `$<-.data.frame`(`*tmp*`, "Weight", value = c(3.83405918042055,  : 
  replacement has 19 rows, data has 20

**Comment by strengejacke** [comment]
Which package versions do you use? I cannot reproduce this with my current setup.

**Comment by MilaniC** [comment]
Thank you for the prompt response.
The issue for me seems to be with ```model_parameters()```

Versions as follows:

Attaching packages: easystats 0.4.3
✔ insight     0.14.4         ✔ datawizard  0.2.0.1
✔ bayestestR  0.11.0     ✔ performance 0.7.3  
✔ parameters  0.14.0    ✔ effectsize  0.4.5  
✔ modelbased  0.7.0     ✔ correlation 0.7.0  
✔ see         0.6.7             ✔ report      0.3.5

**Comment by MilaniC** [comment]
Problem solved.

Yesterday I used:

```install.packages("easystats", repos = "https://easystats.r-universe.dev")```

But ```parameters``` and ```report``` were old versions.

Reinstalled both individually to updated GitHub versions s few moments ago and all good.

Apologies for wasting your time Daniel.
