### ISSUE TITLE
How to test a plotting package

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#2]
Testing plotting is not straightforward. This issue to discuss some ideas and gather information.

- https://stackoverflow.com/questions/31038709/how-to-write-a-test-for-a-ggplot-plot

**Comment by strengejacke** [comment]
For me, this has a rather low priority... If the plot looks OK, I think we're done. Or would you say we need more tests? I would rather spend resources for tests that are "more important".

**Comment by DominiqueMakowski** [comment]
Due to our limited resources, yes I definitely agree. 

(We really should organize some sort of hackathon or something with students and interns that could train their coding/githubing through such improvements haha)

**Comment by mattansb** [comment]
> (We really should organize some sort of hackathon or something with students and interns that could train their coding/githubing through such improvements haha)

🤣
