### ISSUE TITLE
move `{ggridges}` from `Imports` to `Suggests`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#203]
In keeping with the `{easystats}` dependency philosophy. 

Note that we don't even by default download our own `{see}` package in our core packages (like `{parameters}`) and ask the users to install it when needed. I see no reason why we shouldn't be doing the same with this package. The _only_ external hard dependency `{easystats}` ecosystem should have is `{ggplot2}`. That's it! That's the only exception we make. 

To do: Just add `insight::check_if_installed("ggridges")` calls to all relevant contexts.

**Comment by bwiernik** [comment]
We could also switch to just using ggdist consistently for distribution visualizing
