### ISSUE TITLE
global CI/CD failure

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#206]
@strengejacke Do you know why everything is failing with the error below, even if I am relying on devel versions of our packages?

```r
Error: 'data_relocate' is not an exported object from 'namespace:insight'
```

**Comment by strengejacke** [comment]
The reason is that

> 'data_relocate' is not an exported object from 'namespace:insight'

**Comment by strengejacke** [comment]
Is this still an issue?

**Comment by IndrajeetPatil** [comment]
Can you please trigger the CI one more time?

I am on my phone, so can't do it right now.

**Comment by IndrajeetPatil** [comment]
Builds are succeeding, even if the pkgdown is still failing. So this can be closed for now.
