### ISSUE TITLE
modelbased still throwing "Plots are coming in the future version."

### ISSUE THREAD

**Issue by salahlotfi** [easystats/see#207]
Hey guys,
I have downloaded the entire easystats packages once via github and once via CRAN. I am getting this "Plots are coming in the future version." message every time I attempt to plot an output of modelbased package. "see" documentations shows that the issue is fixed but I am not sure why I am running into the same problem.

**Comment by IndrajeetPatil** [comment]
Sorry for the trouble.

Can you please try the following, refresh your R session, and then try again?

```r
install.packages("easystats", repos = "https://easystats.r-universe.dev")
```

**Comment by salahlotfi** [comment]
Thanks for your response. I did everything all over again. 
I am running into another issue. This time "estimate_means()" is throwing this error below and I can't run Plot():
"Error: 'data_restoretype' is not an exported object from 'namespace:insight'".

**Comment by IndrajeetPatil** [comment]
@strengejacke I checked all instances of `data_restoretype()` [here](https://github.com/search?q=org%3Aeasystats+data_restoretype&type=code), and none of it uses it from `{insight}` package namespace. So why are we getting this error with the development version of packages?

@DominiqueMakowski I think this whole issue can be avoided by getting `{modelbased}` update on CRAN ASAP.

**Comment by salahlotfi** [comment]
Also, instead of individually loading the easystats packages, I ran library("easystats") and receive the error below:
"Error: package or namespace load failed for ‘easystats’:
 .onAttach failed in attachNamespace() for 'easystats', details:
  call: NULL
  error: package or namespace load failed for ‘report’:
 object ‘skewness’ is not exported by 'namespace:parameters'
In addition: Warning message:
package ‘easystats’ was built under R version 4.1.2 "

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski The GitHub version needs to be on CRAN for this issue to be resolved.

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/easystats/modelbased/issues/165.

Once you update to the recent version of modelbased, this should be fixed.
