### ISSUE TITLE
Have y axis on vif plot (check_model) start at 1

### ISSUE THREAD

**Issue by mattansb** [easystats/see#216]

**Comment by strengejacke** [comment]
probably makes sense. Not only in `check_model()`, but also `plot(check_collinearity())`.

**Comment by strengejacke** [comment]
I did some preparations, and you just need to modify `.plot_diag_vif()`, I think. Just check if `ci_data` is not `NULL`, and then you have the data frame with CIs for plotting.

**Comment by mattansb** [comment]
Sorry, didn't get to this :/

**Comment by strengejacke** [comment]
@bwiernik should we expand the axis so the full CI is included? See https://easystats.github.io/see/articles/performance.html#check-for-multicollinearity---variance-inflation-factor

The maximum upper CI is ~16.85

**Comment by bwiernik** [comment]
No worries Mattan, I was procrastinating. 

I think it's better to zoom the y axis in on the point estimates, but maybe add arrows for squished CIs

**Comment by strengejacke** [comment]
agreed.
