### ISSUE TITLE
Use of within

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#23]
@mattansb @DominiqueMakowski 

Currently, `plot.see_bayesfactor_models()` uses `within()` to create variables. The help-file, however, states:

> For programming however, i.e., in one's functions, more care is needed, and typically one should refrain from using with(), as, e.g., variables in data may accidentally override local variables, see the reference.

Should we re-write the code in a less beatufiul, non-piped way to avoid `with()` / `within()`?

**Comment by mattansb** [comment]
I'm actually working on this right now - is it okay to use `dplyr` here?

**Comment by strengejacke** [comment]
yes.

**Comment by strengejacke** [comment]
note I have just commited an update, addressing #18
