### ISSUE TITLE
correlation vignette not working?

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#230]
https://github.com/easystats/see/blob/main/vignettes/correlation.Rmd seems to error when building pkgdown, can someone check?

@easystats/maintainers

**Comment by IndrajeetPatil** [comment]
Related issue. 

`select` argument is nor properly specified here:

https://github.com/easystats/see/blob/68b4edd805f34be016ffa1b847d1316ed9d19062/R/theme_radar.R#L14

https://github.com/easystats/see/blob/68b4edd805f34be016ffa1b847d1316ed9d19062/R/coord_radar.R#L13

**Comment by IndrajeetPatil** [comment]
Okay, website is building now.
