### ISSUE TITLE
Readme and Vignette

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#234]
@IndrajeetPatil Any idea why those two fail to build? Do we need to wait for a specific binary being built on CRAN?

**Comment by IndrajeetPatil** [comment]
I think we just need GHA to use the latest versions. Let's see if the build succeed now.

**Comment by etiennebacher** [comment]
This error comes from the vignette "modelbased.Rmd" and more precisely from the call to `emmeans::emtrends()` in `modelbased:::.get_emtrends()`. It is due to the last update of `emmeans` (made on August 5). I can knit this vignette if I downgrade to `emmeans 1.7.5` (current is 1.8.0).

**Comment by etiennebacher** [comment]
Works with `1.7.5`:
``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-40. For overview type 'help("mgcv-package")'.
library(emmeans)

packageVersion("emmeans")
#> [1] '1.7.5'

model <- mgcv::gam(Sepal.Width ~ s(Petal.Length), data = iris)
emmeans::emtrends(model, var = "Petal.Length")
#> 'emmGrid' object with variables:
#>     Petal.Length = 3.758
```

<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Doesn't work with `1.8.0`:
``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-40. For overview type 'help("mgcv-package")'.
library(emmeans)
#> Warning: package 'emmeans' was built under R version 4.2.1

packageVersion("emmeans")
#> [1] '1.8.0'

model <- mgcv::gam(Sepal.Width ~ s(Petal.Length), data = iris)
emmeans::emtrends(model, var = "Petal.Length")
#> Error in emmeans::emtrends(model, var = "Petal.Length"): Variable 'Petal.Length' is not in the dataset
```

<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
Thanks, Etienne. This needs to be resolved in _modelbased_ then. Can you please create an issue there?

At least, the README issue is fixed.

**Comment by etiennebacher** [comment]
But this is more of an issue with `emmeans` right? I can create an issue in `modelbased`, I just don't see what can be done on our side

**Comment by IndrajeetPatil** [comment]
Yeah, true. Please create an issue in _emmeans_ then. Closing this issue in favour of that.

Thanks!

**Comment by etiennebacher** [comment]
For reference: https://github.com/rvlenth/emmeans/issues/369

**Comment by etiennebacher** [comment]
FYI this is fixed in the latest github version of `emmeans`
