### ISSUE TITLE
plot.see_parameters_model: option to turn off group colours for dot-and-whisker plots

### ISSUE THREAD

**Issue by egouldo** [easystats/see#235]
Can the colours for CI groups (`< y_intercept` / `> y_intercept`, ref'd below) be made optional? It's not clear to the reader what the colour represents. For these type of coefficient plots I think colour is typically used to represent the significance level of the estimate, so I had to cross-check against the raw values to realise this wasn't the case. 

Also, documentation could be amended to explain this behaviour - I had to toggle off/on the legend and then dig into the function code before I understood how the colours were determined.

https://github.com/easystats/see/blob/622dcb3a87466bc8c5abe0082fcb1e9b747fdf29/R/plot.parameters_model.R#L359-L375

**Comment by nlubock** [comment]
Agreed - this is quite confusing for undocumented behavior. Would be great if this was noted or removed!

**Comment by egouldo** [comment]
Awesome, thanks for your work on this @strengejacke !
