### ISSUE TITLE
Default colors should be replaced when +theme_blackboard() is added to ggplot object

### ISSUE THREAD

**Issue by rishabhshah-92** [easystats/see#237]
A suggestion: the default color for lines, points, etc. should be changed to white as part of the theme_blackboard, theme_abyss, etc. themes that have a dark background.
<img width="722" alt="image" src="https://user-images.githubusercontent.com/62762478/187503863-0ed5829d-69df-4751-9a5e-7a9831dc66da.png">

**Comment by bwiernik** [comment]
Really wish this PR would get merged into ggplot2... https://github.com/tidyverse/ggplot2/pull/2749

**Comment by IndrajeetPatil** [comment]
Check out `{thematic}` package: https://rstudio.github.io/thematic/
