### ISSUE TITLE
we could (and should?) actually add tests for `how_to_plot()` in the future...

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#24]
we could (and should?) actually add tests for `how_to_plot()` in the future...

_Originally posted by @strengejacke in https://github.com/easystats/see/issues/9#issuecomment-493937550_

**Comment by DominiqueMakowski** [comment]
As a matter of fact, we should add tests for many things 😅

**Comment by DominiqueMakowski** [comment]
This new package' aim is somewhat close to what `how_to_plot` is trying to achieve: https://github.com/coolbutuseless/ggreverse

**Comment by strengejacke** [comment]
Do we actually need this function anymore? I mean, the plotting stuff is getting more complex, I don't see the benefit of this function anymore, and I bet in many cases it is returning nonsense.

**Comment by DominiqueMakowski** [comment]
It's a shame, it would have been groundbreaking... But I agree, for complex stuff it is high maintenance, especially if the plot's implementation is not initially thought with the dataplot->plot workflow in mind

**Comment by strengejacke** [comment]
moved it to WIP, maybe, when this package has a solid base, we can think about refactoring the code and add back that function.
