### ISSUE TITLE
Add `ncol` or `nrow` to `plot.see_check_model()`

### ISSUE THREAD

**Issue by mattansb** [easystats/see#260]
The plot for `check_model()` is quite "tall" - would be nice to have it wider, or better yet - controllable by the user.

**Comment by strengejacke** [comment]
For now, you can return each panel as single plot and compose it in a way you want. But we have:

```r
  if (panel) {
    pw <- plots(p, n_columns = 2)
    .safe_print_plots(pw)
    invisible(pw)
  } else {
    return(p)
  }
```

so we could simply add an `n_column` argument (not sure right now how this is named in other functions, but we have this in several plotting functions).

**Comment by bwiernik** [comment]
I'll add arguments to control the dimensions

**Comment by strengejacke** [comment]
We have an `n_column` argument meanwhile.
