### ISSUE TITLE
Option to only select fixed effects when plotting paramters of `gam()` model

### ISSUE THREAD

**Issue by RoelVerbelen** [easystats/see#265]
The plot of the smooth terms if empty and not useful. 

Worthwhile considering removing this altogether or perhaps extending the use of the `compoment` argument to select only fixed effects (e.g. `plot(result, component = "conditional")`)?

``` r
library(parameters)
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-39. For overview type 'help("mgcv-package")'.
m <- gam(mpg ~ s(wt) + cyl + gear + s(disp), data = mtcars)
result <- model_parameters(m)
result
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |         95% CI | t(20.48) |      p
#> ---------------------------------------------------------------------
#> (Intercept) |       31.22 | 4.54 | [21.77, 40.67] |     6.88 | < .001
#> cyl         |       -2.04 | 0.70 | [-3.50, -0.58] |    -2.91 | 0.008 
#> gear        |        0.40 | 0.58 | [-0.80,  1.61] |     0.70 | 0.494 
#> 
#> # Smooth Terms
#> 
#> Parameter          |    F |   df |     p
#> ----------------------------------------
#> Smooth term (wt)   | 4.81 | 1.00 | 0.040
#> Smooth term (disp) | 5.39 | 7.52 | 0.001
plot(result)
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/6vn1Gqw.png)

<sup>Created on 2023-01-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by RoelVerbelen** [comment]
Current workaround would be:

``` r
library(dplyr)

result %>% 
  filter(Component == "conditional") %>% 
  plot()
```

![](https://i.imgur.com/WVqKkuT.png)

<sup>Created on 2023-01-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
We first have to include this argument in `model_parameters()` (we have it in `?insight::get_parameters`), then it should be easy to do.
