### ISSUE TITLE
plot for check_model()

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#28]
what about this? Any suggestion for different themes / color scales? You need latest performance and see from GitHub...

``` r
library(lme4)
#> Loading required package: Matrix
library(see)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
library(performance)

data(sleepstudy)
sleepstudy$mygrp <- sample(1:5, size = 180, replace = TRUE)
sleepstudy$mysubgrp <- NA
for (i in 1:5) {
  filter_group <- sleepstudy$mygrp == i
  sleepstudy$mysubgrp[filter_group] <-
    sample(1:30, size = sum(filter_group), replace = TRUE)
}

sleepstudy$x1 <- rnorm(nrow(sleepstudy))
sleepstudy$x2 <- runif(nrow(sleepstudy))

m <- lmer(
  Reaction ~ Days + x1 + x2 + (1 | mygrp / mysubgrp) + (1 | Subject),
  data = sleepstudy
)
#> boundary (singular) fit: see ?isSingular

check_model(m)
```

![](https://i.imgur.com/jENDzH2.png)

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
QQ-plot for random effects are in development...

**Comment by strengejacke** [comment]
![image](https://user-images.githubusercontent.com/26301769/58828298-6e208080-8645-11e9-8af8-e5d8978aa7db.png)

**Comment by strengejacke** [comment]
Things have changed slightly again, better you update packages from CRAN, than run the above example.

@pdwaggoner what do you think? My impression is you perform model checks more or less frequently.

**Comment by pdwaggoner** [comment]
I really like this! My only thought is, as a user, I would like to grab/print each one of these plots individually in addition to printing altogether. Is this possible in its current form? If so, I say go with it! Impressive work.

**Comment by pdwaggoner** [comment]
I also really like the subtitles with instructive/diagnostic notes, e.g., for the QQ plot, "data should be plotted along the line." Right in line with the easystats-way.

**Comment by strengejacke** [comment]
I added some arguments to `check_model()`. With `panel = FALSE` you can plot each plot individually.

Not sure if `panel` is the most intuitive name, though.

**Comment by pdwaggoner** [comment]
Perfect! I think panel is fine, or alternatively, if you're using `gridextra` for stacking `ggplot2` objects, you could change the name to `grid`. Not sure how you're doing it specifically, but I would say either sounds fine to me!

**Comment by DominiqueMakowski** [comment]
I love the plots. And same, the informative subtitles are perfect :)

Great job!!

**Comment by strengejacke** [comment]
ok, included outliers in the check-plot:

![Rplot](https://user-images.githubusercontent.com/26301769/58857744-3c8bd180-86a6-11e9-98dc-245edd6320a9.png)

**Comment by DominiqueMakowski** [comment]
That's beautiful 😍

**Comment by strengejacke** [comment]
for non-mixed models, the panel-plot a bit clearer ;-)

``` r
library(see)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
library(performance)

# select only mpg and disp (continuous)
mt1 <- mtcars[, c("disp", "mpg", "hp", "gear")]
# create some fake outliers and attach outliers to main df
mt2 <- rbind(mt1, data.frame(mpg = c(37, 40), disp = c(300, 400), gear = c(4, 4), hp = c(100, 100)))
# fit model with outliers
model <- lm(disp ~ mpg + hp + gear, data = mt2)

check_model(model)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 30 rows containing missing values (geom_text).
```

![](https://i.imgur.com/XX4Kqsz.png)

<sup>Created on 2019-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pdwaggoner** [comment]
Love it! Good clean implementation. Glad the idea fit well with the current updates! Thanks also for taking this past the finish line for me, as it got a bit late on my end.

**Comment by strengejacke** [comment]
The _see_ package still has some time to develop. We indeed have this strange setting that packages like _performance_ or _bayestestR_ have function that also have a `plot()`-method in _see_, however, this plot-method is not yet available... So every now and then we will have some days / weeks, where functions in pkg lack plotting-capabilities, which are some time later shipped with the next _see_ update.
