### ISSUE TITLE
Plot method for `data_tabulate()`?

### ISSUE THREAD

**Issue by etiennebacher** [easystats/see#289]
Asked in easystats/datawizard#419 

It would be nice to have a plot method to do this:

``` r
library(ggplot2)
library(datawizard)

# Data Tabulate

## Desired input
dt <- data_tabulate(mpg, select = c("cyl", "drv"))
### Option 1: plot(dt)
### Option 2: data_tabulate(mpg, select = c("cyl", "drv"), plot = TRUE)

## Desired output
mpg |> 
  data_select(select = c("cyl", "drv")) |> 
  data_to_long() |> 
  ggplot(aes(x = value)) +
  facet_wrap(~name, scales = "free") +
  geom_bar()
```

![](https://i.imgur.com/5jgJfOR.png)

<sup>Created on 2023-05-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by etiennebacher** [comment]
@strengejacke I feel like this is very close to `sjlabelled::plot_frq()`, maybe there's a way to simply reuse this code?

**Comment by strengejacke** [comment]
I wrote sjPlot years ago, I don't think we want to use that code 😉
