### ISSUE TITLE
Plot Cooks distance

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#29]
This is some great stuff - I really like the new `check_*` family. In this vein, I wrote a function to check for influential observations via cook's distance. Its in a similar flavor as your measures @strengejacke , and also includes options to print names of outliers, drop outliers (and write a new df), and plot cook's distance.

I would welcome any thoughts here or whether this is even a desired "check". Thanks all!

``` r
check_outliers <- function(model, print_outliers = TRUE, drop_outliers = FALSE, plot = TRUE) {
  data <- insight::get_data(model)
  n <- nrow(data)
  
  #calculate cook's distance
  cook <- stats::cooks.distance(model)
  o <- length(as.numeric(names(cook)[(cook > (4/n))]))
  outliers <- ifelse(o >= 1, 1, 0)
  
  # check for outliers via cook's distance
  if (outliers >= 1) {
    insight::print_color(sprintf("Warning: Outliers detected.\n"), 'red')
  } else insight::print_color(sprintf("OK: No outliers detected.\n"), 'green')
  
  #option to print names of outliers
  if (print_outliers == TRUE) {
    print((names(cook)[(cook > (4 / n))]))
  }
  
  # option to drop outliers and write a new data frame (- outliers)
  if (drop_outliers == TRUE) {
    data_dropped <- data[!(cook > (4 / n)), ]
    return(data_dropped)
  }
  
  # option to plot cook's distance values, with line denoting likely outliers
  if (plot == TRUE){
    plot(cook, pch = 19, 
         main = "Check for Influential Observations\n(Cook's Distance)",
         ylab = "Cook's Distance Value")
    abline(h = (4 / n), 
           col = "red",
           cex = 4)
    text(x = 1:length(cook) + 1, 
         y = cook, 
         labels = ifelse(cook > (4 / n), 
                         names(cook), ""), 
         col = "red")
  }
}

# example
mt1 <- mtcars[, c(1,3)]  # select only mpg and disp (continuous)
oo <- data.frame(mpg = c(37, 40), # create some fake outliers
                 disp = c(300, 400))
mt2 <- rbind(mt1, oo)  # attach outliers to main df
model <- lm(disp ~ mpg, data = mt2) # fit model with outliers

# call the function
check_outliers(model, print_outliers = TRUE, drop_outliers = FALSE, plot = TRUE)
#> Warning: Outliers detected.
#> [1] "1" "2"
```

![](https://i.imgur.com/Dafuo2Q.png)

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

_Originally posted by @pdwaggoner in https://github.com/easystats/performance/issues/31#issuecomment-498401089_

**Comment by strengejacke** [comment]
I'm just wondering how we can return an object from `check_outlier()`, that stores the data and can be used for plotting? Currently, there's no real return-value for `check_outlier()`, except when the data w/o outliers is returned.

But what could be a return-value when `drop_outliers = FALSE`? @DominiqueMakowski @pdwaggoner ideas?

**Comment by pdwaggoner** [comment]
So the way I was imagining it was the main return value being a list of outliers (i.e., `cd > 4/n`). The second return value was the plot. These choice are in line with the intuition behind the use of Cook's Distance (and other similar metrics for determining outliers), which is simply descriptive and is meant only to show the research where problematic observations _could be_. However, these types of methods are not meant, necessarily to actually filter data, though this could be a second-order use of them. Hence, the `drop_outliers = TRUE` argument was intended to offer researchers some automated help if they indeed wanted to just delete these observations (a relatively risky strategy in any research project, in my opinion). But the main return values were always only intended to be descriptions of possible outlying observations via listing (i.e., `print_outliers = TRUE`) and visually (i.e., in the original function, `plot = TRUE`).

Thus, I think for the plot iteration of this function, like we discussed earlier, I can just create a `ggplot2` version of the original plot idea I had. What do you think of this?

**Comment by DominiqueMakowski** [comment]
> I'm just wondering how we can return an object from check_outlier(), that stores the data and can be used for plotting? Currently, there's no real return-value for check_outlier(), except when the data w/o outliers is returned.

I would agree that we might want to return something. One obvious thing would be to return a dataframe of the same size than the data, with the "distance" value for all observations and eventually a second column with the classification based on some threshold (containing TRUE / FALSE based on whether the observation is considered as an outlier). This return could easily be directly be cbinded to the original data for users to use these "outliers" values as they want. 

Thus I would remove the `drop_outliers` and simply by default return a dataframe with TRUE/FALSEs of the dataframe, that can then be easily (and *explicitly*) filtered by the user.

**Comment by pdwaggoner** [comment]
Here is a quick rendering in `ggplot2` with tw plotting options (I am sure there is a more elegant way of coming up with multiple plot types - but this is a quick option for descriptive purposes at the moment):

``` r
plot_outlier <- function(x, hist = FALSE, ...) {
  data <- insight::get_data(x)
  n <- nrow(data)
  
  cook <- stats::cooks.distance(x)
  o <- length(as.numeric(names(cook)[(cook > (4 / n))]))
  outliers <- ifelse(o >= 1, 1, 0)
  
  if (hist == TRUE) {
    # histogram
    ggplot2::quickplot(cook, 
                       geom = "histogram", 
                       main = "Check for Influential Observations\n(Cook's Distance)", 
                       xlab = "Cook's Distance Values",
                       ylab = "Count of Observations",
                       bins = 50) + 
      ggplot2::theme_bw() + 
      ggplot2::geom_vline(xintercept = (4 / n), 
                          linetype="dashed", 
                          color = "red")
  } else {
    # scatterplot
    ggplot2::quickplot(1:length(cook), cook, 
                       main = "Check for Influential Observations\n(Cook's Distance)", 
                       xlab = "Index",
                       ylab = "Cook's Distance Values") + 
      ggplot2::theme_bw() + 
      ggplot2::geom_hline(yintercept = (4 / n), 
                          linetype="dashed", 
                          color = "red") +
      ggplot2::geom_text(ggplot2::aes(label = ifelse(cook > (4 / n), 
                                                     names(cook), "")), 
                         nudge_x = 0.05,
                         nudge_y = 0.05,
                         check_overlap = TRUE,
                         color = "black")
  }
  
}


# example
mt1 <- mtcars[, c(1,3)]  # select only mpg and disp (continuous)
oo <- data.frame(mpg = c(37, 40), # create some fake outliers
                 disp = c(300, 400))
mt2 <- rbind(mt1, oo)  # attach outliers to main df
model <- lm(disp ~ mpg, data = mt2) # fit model with outliers

# call the function for a scatterplot (hist = FALSE)
plot_outlier(model, hist = FALSE)
```

![](https://i.imgur.com/w84Vkmk.png)

``` r

# call the function for a histogram (hist = TRUE)
plot_outlier(model, hist = TRUE)
```

![](https://i.imgur.com/Fz3Ovfi.png)

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pdwaggoner** [comment]
Also - @DominiqueMakowski , great suggestion. So something like this for the `check_outlier()` function (by the by, @strengejacke suggested the singular `check_outlier`, instead of my original plural `check_outliers`... you'll have to take it up with him ;) ):

``` r
check_outlier.default <- function(x, print_outliers = TRUE, drop_outliers = FALSE, ...) {
  data <- insight::get_data(x)
  n <- nrow(data)
  
  cook <- stats::cooks.distance(x)
  o <- length(as.numeric(names(cook)[(cook > (4 / n))]))
  outliers <- ifelse(o >= 1, 1, 0)
  
  if (outliers >= 1) {
    insight::print_color(sprintf("Warning: Outliers detected.\n"), 'red')
  } else insight::print_color(sprintf("OK: No outliers detected.\n"), 'green')
  
  if (print_outliers == TRUE) {
    print((names(cook)[(cook > (4 / n))]))
  }
  
  if (drop_outliers == TRUE) {
    data_dropped <- data[!(cook > (4 / n)), ]
    return(data_dropped)
  }
  
  cook_df <- as.data.frame(cook)
  names(cook_df)[names(cook_df) == 'cook'] <- "Cook's Distance"
  
  return(cook_df)
}

# example
mt1 <- mtcars[, c(1,3)]  # select only mpg and disp (continuous)
oo <- data.frame(mpg = c(37, 40), # create some fake outliers
                 disp = c(300, 400))
mt2 <- rbind(mt1, oo)  # attach outliers to main df
model <- lm(disp ~ mpg, data = mt2) # fit model with outliers

check_outlier.default(model)
#> Warning: Outliers detected.
#> [1] "1" "2"
#>                     Cook's Distance
#> Mazda RX4              8.373358e-03
#> Mazda RX4 Wag          8.373358e-03
#> Datsun 710             1.878066e-02
#> Hornet 4 Drive         6.590235e-04
#> Hornet Sportabout      1.524208e-02
#> Valiant                2.471897e-03
#> Duster 360             1.054772e-02
#> Merc 240D              6.434924e-03
#> Merc 230               9.636918e-03
#> Merc 280               1.095632e-02
#> Merc 280C              1.626432e-02
#> Merc 450SE             2.210870e-05
#> Merc 450SL             3.470603e-05
#> Merc 450SLC            4.438013e-04
#> Cadillac Fleetwood     9.819605e-02
#> Lincoln Continental    8.217080e-02
#> Chrysler Imperial      5.396506e-02
#> Fiat 128               2.018874e-02
#> Honda Civic            2.615098e-02
#> Toyota Corolla         2.113238e-02
#> Toyota Corona          1.760252e-02
#> Dodge Challenger       2.158789e-03
#> AMC Javelin            4.884473e-04
#> Camaro Z28             6.073828e-03
#> Pontiac Firebird       3.031182e-02
#> Fiat X1-9              2.673405e-02
#> Porsche 914-2          1.132261e-02
#> Lotus Europa           1.524005e-02
#> Ford Pantera L         9.521780e-03
#> Ferrari Dino           1.549708e-02
#> Maserati Bora          2.273649e-04
#> Volvo 142E             1.757278e-02
#> 1                      4.231311e-01
#> 2                      1.753209e+00
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
> Thus I would remove the drop_outliers and simply by default return a dataframe with TRUE/FALSEs of the dataframe, that can then be easily (and explicitly) filtered by the user.

Good idea! This can be done before submission.

**Comment by strengejacke** [comment]
The histogram looks nice, this is what I would implement in _see_.

**Comment by strengejacke** [comment]
``` r
library(see)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
library(performance)

# select only mpg and disp (continuous)
mt1 <- mtcars[, c(1,3)]
# create some fake outliers and attach outliers to main df
mt2 <- rbind(mt1, data.frame(mpg = c(37, 40), disp = c(300, 400)))
# fit model with outliers
model <- lm(disp ~ mpg, data = mt2)

x <- check_outliers(model)

x
#> Warning: Outliers detected (cases 33, 34).

plot(x)
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 32 rows containing missing values (geom_text).
```

![](https://i.imgur.com/ersq5CM.png)

``` r

plot(x) + theme_lucid()
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 32 rows containing missing values (geom_text).
```

![](https://i.imgur.com/uEQVc1l.png)

<sup>Created on 2019-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pdwaggoner** [comment]
This looks great! Good updates and also I like the different color for outliers. Just saw the code in `.../R`. Did you want a scatterplot as well? Or just the histogram? No preference on my end. Thanks!

**Comment by strengejacke** [comment]
I think one plot-type is enough, and I personally preferred your histogram-style, because you can easily grasp the proportion of "good" and "outlier" values. Especially for large data sets, I think the histogram is easier to catch, because the x-axis is not number of observations, but the distance value.

**Comment by pdwaggoner** [comment]
Makes sense - sounds good to me. Glad you're happy with it.

**Comment by DominiqueMakowski** [comment]
I understand @strengejacke arguments for the histogram. Nevertheless, I find the dot plots aesthetically more pleasing, and having a dot per observation also is intuitive in its way... I wonder if there would be a way to combine the two. 

Maybe with a [raincloud plot](https://micahallen.org/2018/03/15/introducing-raincloud-plots/)? We could display such raincloud horizontally, and add the threshold value as a vertical line (as currently in the histogram), and fill all the "outlier" part of the points and the density curve with a different colour. This way we would still see the distribution, but also all individual points? If that makes sense I could take a look into it (I need an occasion to dive into raincloud plots)

**Comment by jmbarbone** [comment]
I just ran into the same issue.  It could be an issue with using `subset` inside `lm`.   Subsetting and saving to a different object seems to do the trick.

``` r
library(performance)
x <- data.frame(a = 1:10, b  = 1:10, z = 1:10)

mod <- lm(a ~ poly(b, 2), data = x)
try(check_model(mod))
#> Registered S3 method overwritten by 'see':
#>   method                    from      
#>   plot.visualisation_recipe datawizard

mod <- glm(a ~ poly(b, 2, raw = TRUE), data = x, subset = z > 1)
# this fails -- because of subset?
try(check_model(mod))
#> Error in order(plot_data$Cooks_Distance, decreasing = TRUE): argument 1 is not a vector

x2 <- subset(x, z > 1)
mod <- glm(a ~ poly(b, 2), data = x2)
try(check_model(mod))
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
