### ISSUE TITLE
Improve plot() for check_predictions()

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#290]
For models with integer/categorical outcomes, we could use bars instead of density lines, like in:

https://solomonkurz.netlify.app/blog/2023-05-21-causal-inference-with-ordinal-regression/

![image](https://github.com/easystats/see/assets/26301769/19ee7db3-3a23-4a09-8d7f-b589bfdff664)

**Comment by strengejacke** [comment]
``` r
library(performance)
library(see)
mtcars$vs2 <- factor(letters[mtcars$vs + 1])
model <- glm(vs2 ~ wt + mpg, data = mtcars, family = "binomial")

plot(check_predictions(model))
```

![](https://i.imgur.com/WSA0atq.png)

``` r

plot(check_predictions(model), type = "dots")
```

![](https://i.imgur.com/AUq5kLS.png)

``` r

## Dobson (1990) Page 93: Randomized Controlled Trial :
counts <- c(18, 17, 15, 20, 10, 20, 25, 13, 12)
outcome <- gl(3, 1, 9)
treatment <- gl(3, 3)
d <- data.frame(treatment, outcome, counts) # showing data
model <- glm(counts ~ outcome + treatment, family = poisson(), data = d)

plot(check_predictions(model))
```

![](https://i.imgur.com/Jnm76cP.png)

``` r

plot(check_predictions(model), type = "dots")
```

![](https://i.imgur.com/viwsmVZ.png)

<sup>Created on 2023-05-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
``` r
library(performance)
library(see)
library(glmmTMB)

data(Salamanders)
m1 <- glmmTMB(count ~ mined + (1 | site),
  zi = ~mined,
  family = poisson, data = Salamanders
)

plot(check_predictions(m1))
```

![](https://i.imgur.com/IlGKieb.png)

``` r

plot(check_predictions(m1), type = "dots")
```

![](https://i.imgur.com/tRZAs5R.png)

<sup>Created on 2023-05-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Maybe this example is quite good to demonstrate why dots can be more useful than lines in some situations:

``` r
library(performance)
library(see)

set.seed(99)
d <- iris
d$skewed <- rpois(150, 1)
m2 <- glm(skewed ~ Species + Petal.Length + Petal.Width, data = d, family = poisson())
out <- check_predictions(m2)
plot(out)
```

![](https://i.imgur.com/5wb5zt1.png)

``` r
plot(out, type = "dots")
```

![](https://i.imgur.com/r47Ycjk.png)

<sup>Created on 2023-05-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
Thanks for taking the initiative on this! Really happy to see this added.

I like the use of the green dot and thin line rather than the bars for the observed data. It feels more consistent with the density.

Comparing the design of the `bayesplot::ppc_bars()` (what's shown in the first post), I can see the benefits of both the "replications as median+interval" and "replications as dots" options. I think the median+interval option is easier for a quick check (is the observed value in the interval), but the 

Could we support both? Perhaps have options `type = c("density", "discrete_dots", "discrete_interval", "discrete_both")`, where "density" is the original continuous density method, "discrete_dots" is what you have implemented, "discrete interval" replaces the dots with a cross-bar with the median replication value and a `ci` percent interval bar, and "discrete_both" has both dots and intervals?

For all of these options, I think the green line for observed data should be added last to the plot so that it is on top and not obscured by the replication lines/dots.

**Comment by DominiqueMakowski** [comment]
The dot plot lacks a legend to clarify which points are "model predictions" and which is the observed one.

**Comment by strengejacke** [comment]
True, why didn't I realize that? 🙄

**Comment by strengejacke** [comment]
``` r
library(performance)
library(see)

set.seed(99)
d <- iris
d$skewed <- rpois(150, 1)
m2 <- glm(skewed ~ Species + Petal.Length + Petal.Width, data = d, family = poisson())
out <- check_predictions(m2)

plot(out)
#> The model has an integer or a categorical response variable.
#>   It is recommended to switch to a dot-plot style, e.g.
#>   `plot(check_model(model), type = "discrete_dots"`.
```

![](https://i.imgur.com/krNDuJ5.png)

``` r

plot(out, type = "discrete_dots")
```

![](https://i.imgur.com/xQ9DhdJ.png)

``` r

plot(out, type = "discrete_interval")
```

![](https://i.imgur.com/Pr2qkeD.png)

``` r

plot(out, type = "discrete_both")
```

![](https://i.imgur.com/ad9y12w.png)

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
See the updated subtitle for intervals:

``` r
library(performance)
library(see)

set.seed(99)
d <- iris
d$skewed <- rpois(150, 1)
m2 <- glm(skewed ~ Species + Petal.Length + Petal.Width, data = d, family = poisson())
out <- check_predictions(m2)
plot(out, type = "discrete_interval")
```

![](https://i.imgur.com/5hxVwou.png)

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Maybe simple dots are enough for the observed data  points?

``` r
library(performance)
library(see)

set.seed(99)
d <- iris
d$skewed <- rpois(150, 1)
m2 <- glm(skewed ~ Species + Petal.Length + Petal.Width, data = d, family = poisson())
out <- check_predictions(m2)
plot(out)
#> The model has an integer or a categorical response variable.
#>   It is recommended to switch to a dot-plot style, e.g.
#>   `plot(check_model(model), type = "discrete_dots"`.
```

![](https://i.imgur.com/HdKtUka.png)

``` r

plot(out, type = "discrete_dots")
```

![](https://i.imgur.com/hZg4RyX.png)

``` r

plot(out, type = "discrete_interval")
```

![](https://i.imgur.com/aTleBoQ.png)

``` r

plot(out, type = "discrete_both")
```

![](https://i.imgur.com/2MwJUyG.png)

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
``` r
library(performance)
library(see)

set.seed(99)
d <- iris
d$skewed <- rpois(150, 1)
m2 <- glm(skewed ~ Species + Petal.Length + Petal.Width, data = d, family = poisson())
out <- check_predictions(m2)
plot(out) + theme_blackboard()
#> The model has an integer or a categorical response variable.
#>   It is recommended to switch to a dot-plot style, e.g.
#>   `plot(check_model(model), type = "discrete_dots"`.
```

![](https://i.imgur.com/IE9NmBT.png)

``` r

plot(out, type = "discrete_dots") + theme_blackboard()
```

![](https://i.imgur.com/FBvEQN9.png)

``` r

plot(out, type = "discrete_interval") + theme_blackboard()
```

![](https://i.imgur.com/MP5KBSh.png)

``` r

plot(out, type = "discrete_both") + theme_blackboard()
```

![](https://i.imgur.com/VQfapjD.png)

``` r
Ȁ
#> Error in eval(expr, envir, enclos): object 'Ȁ' not found
```

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
