### ISSUE TITLE
Rotate x-axis labels by default for plot method for `check_outliers()`

### ISSUE THREAD

**Issue by rempsyc** [easystats/see#317]
For the outliers paper, we have to add manual `ggplot2` code to the plot method for `check_outliers()` so that the labels don't overlap. Reprex:

``` r
library(performance)
library(see)

x <- check_outliers(mtcars)
plot(x)
```

![](https://i.imgur.com/eQu3yvT.png)

``` r

# Correction:
plot(x) + 
  ggplot2::theme(axis.text.x = ggplot2::element_text(
    angle = 45, size = 8
  ))
```

![](https://i.imgur.com/62iSlEJ.png)

<sup>Created on 2024-01-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Would it make sense to make this the default?

Later on we can tackle #262 properly but for now that should be an improvement already?

**Comment by IndrajeetPatil** [comment]
Alternatively, we could use [`n.dodge`](https://ggplot2.tidyverse.org/reference/guide_axis.html) argument and set it to `2`.

**Comment by rempsyc** [comment]
Result for reference:

``` r
library(performance)
library(see)

x <- check_outliers(mtcars)
plot(x) + 
  ggplot2::guides(x = ggplot2::guide_axis(n.dodge = 2))
```

![](https://i.imgur.com/tIV1sLC.png)

<sup>Created on 2024-01-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Yeah I think it could work too
