### ISSUE TITLE
CRAN 0.2.0

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#32]
There is no hurry, but I think we have added all necessary stuff for forthcoming updates of our other packages (https://github.com/easystats/see/blob/master/NEWS.md), so I think, in general the next release of _see_ is ready.

Any preferences regarding time frame, any stuff missing? @DominiqueMakowski @mattansb @pdwaggoner

**Comment by mattansb** [comment]
All is good on my end, unless @DominiqueMakowski wants to try and implement the ***pizza*** #16 😎

**Comment by pdwaggoner** [comment]
Did you want to add anything about (minor) updates to `how_to_plot()`? 

Otherwise looks great!

**Comment by strengejacke** [comment]
`how_to_plot()` indeed needs some love... But I realized that not all plotting methods fit into the `data_plot()`-concept, thus making it difficult to make it work with `how_to_plot()`.

**Comment by pdwaggoner** [comment]
Yeah that makes sense. We can certainly revisit this after this release. As such, from my perspective, I would say its good to go!

**Comment by DominiqueMakowski** [comment]
> All is good on my end, unless @DominiqueMakowski wants to try and implement the pizza #16 😎

😭 

> how_to_plot() indeed needs some love...

Yes, I would like to improve it, but my priority currently lies with releasing parameters and ultimately fixing `report`. This can wait a bit. In the future we will investigate where and how to dissociate the data from the plotting (although I would love to expose some of the performance plotting code for personal re-use 😏)

greenlight on my side 🚀

**Comment by strengejacke** [comment]
I wait until we fixed everything in the vignettes in bayestestR, so we don't have any bugs when releasing both bayestestR and see. Then we also have the new plotting-methods available, for performance and bayestestR.
