### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#320]
@IndrajeetPatil What do you think about submitting a new release to CRAN the next days? I'm planning to submit _parameters_, but that would break _see_ (nothing to do here, the dev-version of _see_ has already fixed this issue). So we would need to submit both packages within a certain time frame.

**Comment by IndrajeetPatil** [comment]
Sure, just let the CRAN team know that you’ve informed the maintainer and
the update is on the way for broken package. I can then update *see* once
*parameters* update is on CRAN.

**Comment by strengejacke** [comment]
Ok parameters is on CRAN

**Comment by strengejacke** [comment]
We could merge #321 before submission.

**Comment by strengejacke** [comment]
ok, I think you can submit. I also need to submit a hotfix of _parameters_ due to breaking changes in _marginaleffects_. Should we submit _see_ first, then _parameters_ hotfix, or other way around?

**Comment by strengejacke** [comment]
_parameters_ on CRAN!
