### ISSUE TITLE
CRAN failures

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#325]
See https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/see-00check.html

Seems like ggside is failing (https://cran.r-project.org/web/checks/check_results_ggside.html) since the latest ggplot2 update.

**Comment by IndrajeetPatil** [comment]
Yes, I have already created an issue in the repo to track this.

**Comment by IndrajeetPatil** [comment]
https://github.com/jtlandis/ggside/issues/56

**Comment by IndrajeetPatil** [comment]
_ggside_ update is on CRAN, and it should fix the problems: https://cran.r-project.org/web/packages/ggside/index.html

I will still keep this issue open to remind us to update the snapshots for changes in _ggplot2_ and _ggside_.
