### ISSUE TITLE
Vignette / docs / examples

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#33]
I think some of the plot-functions can be described in more details. Even me as package maintainer is struggling with some of the arguments ;-) especially for `plot.bayesfactor_models()`.

**Comment by mattansb** [comment]
I'll get to this after the current BF re-structuring at bayestestR is finalized 👍

**Comment by strengejacke** [comment]
I have drafted some vignettes (https://easystats.github.io/see/articles/), which, however, will not be part of the package, but only available at the website (for now).

But, if you want to get back to this issue, maybe you can just add some documented code-chunks to [this vignette](https://easystats.github.io/see/articles/bayestestR.html#bayes-factors-bfs)?

**Comment by mattansb** [comment]
Wow, I totally forgot to get back to this! Sorry!

I'll go over the vignette right now.

**Comment by strengejacke** [comment]
There's no hurry, we can add content to the vignette every now and then, I think... I just stumbled over this issue in preparation of the next CRAN submission ;-)
