### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#330]
Given all the latest improvements for model checks (https://github.com/easystats/performance/pull/643), and the newly implemented `plot()` methods in _see_, I would probably like to submit new releases of _performance_ and _see_ to CRAN. WDYT @IndrajeetPatil ?

**Comment by IndrajeetPatil** [comment]
Sure, fine by me. 

Should I submit it today, or do you plan to add a few more things to _see_ before?

**Comment by strengejacke** [comment]
I think performance needs to be submitted first. I'll post here when performance is on CRAN

**Comment by strengejacke** [comment]
_performance_ is on CRAN.
