### ISSUE TITLE
Finalize draft for plot.point_estimate()

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#35]
> I like this idea. Maybe something like: which_estimates(c("All", "Median", "Mean", "MAP"))

We could derive this from bayestestR::point_estimate(), where this argement is named centrality. We could then save the option as attribute, and reading that attribute in the plot-method.

(https://github.com/easystats/see/commit/0502ac047858d56db0a142b280dcb2161723282d)

**Comment by strengejacke** [comment]
@DominiqueMakowski @pdwaggoner 
Draft is finished now, I think, but I couldn't get `ggrepel::geom_text_repel()` working as intended (see our discussion https://github.com/easystats/see/commit/0502ac047858d56db0a142b280dcb2161723282d).

it seems that ggrepel only works with mapped aes for x/y, thus it prints the labels thousands of times... For now, we have (sometimes overlapping) `geom_text()`, might be fixed in the future - unless you have any idead?

**Comment by pdwaggoner** [comment]
Apologies for my radio silence - currently in the thick of moving across the country. Will jump back here ASAP. Thanks guys!
