### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#36]
What about creating a DOI for this so it can be properly cited in bayestestR's paper (see [here](https://github.com/easystats/bayestestR/pull/197))?

**Comment by pdwaggoner** [comment]
I would be happy to create the DOI for this @DominiqueMakowski - I use Zenodo for my packages. Would this be alright by you? Also, who should be listed as individual authors (DOI registrys require listing authors)? Maybe everyone in the `DESCRIPTION` file, or others?

**Comment by DominiqueMakowski** [comment]
Don't bother, it's the maintainer's job 😁

**Comment by pdwaggoner** [comment]
Wasn't sure if this was  "community call". Thanks

**Comment by strengejacke** [comment]
https://doi.org/10.5281/zenodo.3352043
