### ISSUE TITLE
Issue plotting lme4 random effects from `model_parameters` 

### ISSUE THREAD

**Issue by DanSimonet** [easystats/see#365]
Amazing suite of packages! I was hoping to pivot my entire mixed modeling workflow to easystats but came across an issue in how `model_parameters` extracts parameter labels (I believe from `broom.mixed`) which prevents plotting of group-specific random effects. I am expecting output similar to `sjPlot` and use this as comparison. 

**Model**

```
library(lme4)
s_mod <- lmer(Reaction ~ Days + (Days|Subject), data = sleepstudy)
```

**Expectation**
```
# Sjplot output
sjPlot::plot_model(s_mod, show.values = T, type = "re", value.offset = 0.5)
```
![image](https://github.com/user-attachments/assets/d5ef305b-96ff-4da4-90a1-58ab576b4cdb)

**Model Parameter + See Result** 
```
# Parameters -> see output
parameters::model_parameters(s_mod, group_level = TRUE) |> plot()
```
![image](https://github.com/user-attachments/assets/c39308b6-71b5-4367-9692-3c1138fad9cb)

**Source**
The problem I believe is `broom.mixed::tidy` returns term and level as different columns. `model_parameters` as a result has a single value for the grouping variable in the `Parameter` column as opposed to the group-specific identifiers which show up in `Level`.

**Comment by strengejacke** [comment]
I think it's because we just haven't a proper `plot()` method for random effects when `group_level = TRUE`. Let me check.

**Comment by strengejacke** [comment]
Rendering is not perfect here, but these are the options:

``` r
library(lme4)
#> Loading required package: Matrix
s_mod <- lmer(Reaction ~ Days + (Days | Subject), data = sleepstudy)

parameters::model_parameters(s_mod, group_level = TRUE) |>
  plot()
```

![](https://i.imgur.com/vXRY5SJ.png)

``` r

parameters::model_parameters(s_mod, group_level = TRUE) |>
  plot(show_labels = TRUE)
```

![](https://i.imgur.com/gN1yerE.png)

``` r

parameters::model_parameters(s_mod, group_level = TRUE) |>
  plot(show_labels = TRUE, size_text = 5)
```

![](https://i.imgur.com/y7q85Q9.png)

``` r

parameters::model_parameters(s_mod, group_level = TRUE) |>
  plot(sort = "ascending", show_labels = TRUE)
```

![](https://i.imgur.com/em2t7yS.png)

``` r

parameters::model_parameters(s_mod, group_level = TRUE) |>
  plot(sort = "ascending", show_labels = TRUE, n_columns = 2)
```

![](https://i.imgur.com/7csXDfx.png)

``` r

parameters::model_parameters(s_mod, group_level = TRUE) |>
  plot(sort = "ascending", show_labels = TRUE, show_intercept = FALSE)
```

![](https://i.imgur.com/QNUkjeG.png)

<sup>Created on 2024-09-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
