### ISSUE TITLE
A JDSSV Paper?

### ISSUE THREAD

**Issue by pdwaggoner** [easystats/see#37]
Hi @DominiqueMakowski and @strengejacke - There was a brand new journal just announced called "Journal of Data Science, Statistics, and Visualisation". I found out about it through the ASA listserv. They announced a call for the first round of papers to be published. There are no APCs and its open source! What do you guys think about preparing and submitting a paper covering an introduction and implementation of `see`? It could be a really cool thing to get easystats in on the ground level of a new journal related to what we all do. 

Here is the homepage: https://jdssv.org/index.php/jdssv

Let me know if you're on board. If so, I would be happy to take the lead on the paper and start drafting. If not, no worries.

**Comment by DominiqueMakowski** [comment]
👍  I am okay for giving it a shot it seems appropriate :) I am curious to know what the others think

**Comment by mattansb** [comment]
Sounds good - I'm all for it.

**Comment by pdwaggoner** [comment]
Sounds good - glad you guys are on board. And I assume the authors would be: me, @strengejacke , @DominiqueMakowski and @mattansb (i.e., those in the `DESCRIPTION` file)?

Let's wait to hear back from @strengejacke and I will proceed accordingly and be in touch, if he's on board. Thanks all!

**Comment by DominiqueMakowski** [comment]
Note to pressure myself: one of the features I would really like to improve and extend, that I feel is a very unique and new perspective for visualisation packages, is the decomposition between data preparation and the plotting itself, implemented through the `data_plot()`, `plot()` and `how_to_plot()` sequence. 

This dissociation provides IMO far greater flexibility to the user (as well as is useful from a didactic/learning perspective), which can figure out what the data is (and how it is transformed to serve visualisation), and can then access, understand and tweak the plotting part to its needs. This two-steps framework could unleash the aesthethic creativity in everyone :sparkles:

This is a "theoretical" or "abstract" aspect that I would like to see mentioned in the paper... but it needs a bit more work to put it in practice and be convincing. All that to say, no need to rush with that paper 😬😅

**Comment by strengejacke** [comment]
In general, I am open and excited to support new journals that are based on an "open philosophy". It would be great if they already have a ISSN. But I don't mind if this is not the case.

**Comment by pdwaggoner** [comment]
Doesn't look like they have an ISSN. This with @DominiqueMakowski ideas on needed additional functionality in `see`, perhaps this is a little over-ambitious? Happy to shelf the idea until the package is ready. Just an idea. Thanks!

**Comment by ejulia17** [comment]
Hi all, I only just came across this journal and there are still not issues. Does anyone have more details? Thanks for any hints what is going on...

**Comment by IndrajeetPatil** [comment]
I am a bit hesitant to go with _JDSSV_. I am not sure if it will give the package the needed visibility and the general readership we covet.

It is rather boring at this point, I recognize that, but I think _JOSS_ might still be the best option for us. It has much broader readership (across behavioral science, biological sciences, etc.), is recognizable, widely read, has no APC either. So it's a win-win proposition. 

But that's my 2 cents. I will yield to the majority opinion here.

**Comment by IndrajeetPatil** [comment]
(If you agree, I can work on getting a working draft ready for _JOSS_.)

**Comment by pdwaggoner** [comment]
Hi @IndrajeetPatil - thanks for the note! Yeah, I agree about the limited value of JDSSV. Since opening this original issue a while ago, I have not been too impressed with the journal. I also like JOSS for the reasons you mentioned. So, for my addition two cents (which is up to *4 cents* now between the two of us), I agree and think we could get moving on a draft for `see`. Let's await word from the other main contributors, I'd say. 

Ping @strengejacke @DominiqueMakowski @mattansb

**Comment by mattansb** [comment]
Sounds fine to me (:

**Comment by strengejacke** [comment]
![picard_make_it_so](https://user-images.githubusercontent.com/26301769/112269099-34849380-8c78-11eb-851b-ba81617d6a90.jpg)

**Comment by IndrajeetPatil** [comment]
Closing in favor of #102
