### ISSUE TITLE
Forest plots for model parameters

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#39]
"Never use more dimensions than your data" - thus, a point-estimate should simply be a point. And then I would add error bars / CI to the plot, so you end up having [forest plots](https://strengejacke.github.io/sjPlot/articles/plot_model_estimates.html).

_Originally posted by @strengejacke in https://github.com/easystats/parameters/issues/65#issuecomment-506609007_

**Comment by DominiqueMakowski** [comment]
The only edge case that I see is in the case of multiple CIs, but we can easily detect that by checking the length of `ci` which is stored in the parameters' attributes, and if length > 1 then pass the whole parameter table to the new `reshape_ci` function, and then simply add the `CI` as a facet... easy peasy

**Comment by mattansb** [comment]
Or plot multiple CIs one on top of each other?
See how something similar is now done in `emmeans` [here](https://github.com/rvlenth/emmeans/issues/131#issuecomment-514435946).

**Comment by DominiqueMakowski** [comment]
Yup, if tastefully implemented it could be nice

**Comment by DominiqueMakowski** [comment]
(tastefully = in a readable and aesthetically pleasing fashion ^^)

**Comment by strengejacke** [comment]
>  if tastefully implemented it could be nice

Like in [sjPlot](https://strengejacke.github.io/sjPlot/articles/plot_model_estimates.html#bayesian-models-fitted-with-stan)?

**Comment by DominiqueMakowski** [comment]
I don't know, does sjPlot handle multiple CIs 😬 ?

Also, by default, I very strongly favour geom_pointrange over error bars (i.e., I find simple lines `------x------`, as opposed to brackets `][------x------][`, sleeker) ☺️

**Comment by DominiqueMakowski** [comment]
@strengejacke I have misread your link, sjPlot also uses pointrange by default and sort-of boxplots to handle 2 different CIs for is that correct?

**Comment by DominiqueMakowski** [comment]
But yes, sjPlot is tasteful ^^ 

Nevertheless, it would be good to deal with multiple CIs in an automatic and systemic way

**Comment by strengejacke** [comment]
For Bayesian models, two HDIs are plotted by default:

![image](https://user-images.githubusercontent.com/26301769/61951477-5c0def00-afb1-11e9-8f63-00390d82fade.png)

I use geom_errorbar(), but you can use the `width`-argument to remove the "brackets" from the line-ends.

**Comment by strengejacke** [comment]
Oh, we need to have information about the link-function (as atribute?), in order to choose the correct scale (see again https://strengejacke.github.io/sjPlot/articles/plot_model_estimates.html).

**Comment by DominiqueMakowski** [comment]
For model parameters? Why the link? It's always identity for model_parameters isn't it

**Comment by strengejacke** [comment]
Ok, I probably was think a bit too far ahead... Usually, in social science, you would rather want to present (e.g.) Odds or Incidence Rate Ratios instead of log-estimates.

**Comment by DominiqueMakowski** [comment]
We can add this feature in the future for sure

**Comment by DominiqueMakowski** [comment]
The plot might also benefit from the `clean_names` attributes (currently used by `parameters_table`).

Note to myself: as matter of fact, [`format_parameters()`](https://github.com/easystats/parameters/blob/master/R/format_parameters.R) might be improved to deal with cases of `s(x)`, `poly(x)` and `bs(x)`.

**Comment by strengejacke** [comment]
This looks also nice, a "completely" different style... 

![EAG_nVLXoAE-ckN](https://user-images.githubusercontent.com/26301769/61956207-ea3ba280-afbc-11e9-87b9-c205a7612efd.png)

**Comment by strengejacke** [comment]
Quick sketch:

``` r
library(ggplot2)
library(parameters)

model <- lm(mpg ~ wt + cyl + gear + hp, data = mtcars)
mp <- model_parameters(model, standardize = "refit")

ggplot(mp, aes(x = Parameter, y = Coefficient)) +
  geom_errorbar(aes(ymin = CI_low, ymax = CI_high), alpha = .3, size = 4, width = 0, color = "#2196F3") +
  geom_segment(aes(y = CI_low, yend = CI_low + .4, x = Parameter, xend = Parameter), size = 4, color = "#2196F3", alpha = .5) +
  geom_segment(aes(y = CI_high, yend = CI_high - .4, x = Parameter, xend = Parameter), size = 4, color = "#2196F3", alpha = .5) +
  see::geom_point2(color = "#2196F3", size = 2.5) +
  coord_flip()+
  see::theme_lucid()
```

![](https://i.imgur.com/2FKWTvS.png)

<sup>Created on 2019-07-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Minimalist is the new maximalist:

``` r
library(ggplot2)
library(parameters)

model <- lm(mpg ~ wt + cyl + gear + hp, data = mtcars)
mp <- model_parameters(model, standardize = "refit")

# mp <- mp[mp$Parameter != "(Intercept)", ]
max_value <- max(abs(mp[["Coefficient"]]))

ggplot(mp, aes(x = Parameter, y = Coefficient, color = Coefficient)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed") +
  geom_pointrange(aes(ymin = CI_low, ymax= CI_high), size = 1) +
  scale_color_gradientn(colours = c("#f44336", "#FF9800", "#4CAF50"), limits=c(-max_value, max_value)) +
  coord_flip() +
  see::theme_modern(legend.position = "none")
```

![](https://i.imgur.com/wVOHhzS.png)

<sup>Created on 2019-07-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
For Multiple CIs is kinda tough to display it on one plot

``` r
library(ggplot2)
library(parameters)
library(rstanarm)

model <- stan_glm(mpg ~ wt + cyl + gear + hp, data = mtcars, refresh = 0)
mp <- model_parameters(model, ci = c(0.5, 0.7, 0.9))
#> Possible multicollinearity between hp and cyl (r = 0.78). This might lead to inappropriate results. See 'Details' in '?rope'.

max_value <- max(abs(mp[["Median"]]))

ggplot(mp, aes(x = Parameter, y = Median, color = Median)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed") +
  geom_pointrange(aes(ymin = CI_low_90, ymax= CI_high_90), size = 0.5) +
  geom_pointrange(aes(ymin = CI_low_70, ymax= CI_high_70), size = 1) +
  geom_pointrange(aes(ymin = CI_low_50, ymax= CI_high_50), size = 2) +
  scale_color_gradientn(colours = c("#f44336", "#FF9800", "#4CAF50"), limits=c(-max_value, max_value)) +
  coord_flip() +
  see::theme_modern(legend.position = "none")
```

![](https://i.imgur.com/Z1U4kPC.png)

<sup>Created on 2019-07-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Current implementation:

``` r
library(parameters)
library(see)

model <- glm(mpg ~ wt + cyl + gear + hp, data = mtcars)
mp <- model_parameters(model)
plot(mp)
```

![](https://i.imgur.com/CxMrhQB.png)

``` r
mp <- model_parameters(model, ci = c(0.5, 0.7, 0.9))
plot(mp)
```

![](https://i.imgur.com/5rJJTum.png)

<sup>Created on 2019-07-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
