### ISSUE TITLE
Namespace scope

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#4]
This will most likely not pass CRAN checks:
`ggplot2:::ggname` 
(https://github.com/easystats/see/blob/master/R/geom_violinhalf.R#L85)

**Comment by DominiqueMakowski** [comment]
Hum. To be honest, I don't have experience with creating new geoms (but that would be a very useful skill though for easystats' visualisation), so I am not sure how to replace this... have you already have CRAN warnings from the use of :::?

**Comment by strengejacke** [comment]
I had this issue quite some time ago, but I'm not sure how it's today. Since CRAN checks are becoming stricter rather than liberal, I would say this causes troubles... I'll check.

**Comment by strengejacke** [comment]
We could also directly use `grid::grobName()`, since `ggname()` is just a wrapper for that.
