### ISSUE TITLE
Improve plots()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#42]
- Remove annoying tableGrobs textual output
- Improve alignment (?)

**Comment by DominiqueMakowski** [comment]
Should we "simply" swap the use of `gridExtra` for `cowplot`?

**Comment by strengejacke** [comment]
we now may also look at the patchwork package. haven't worked with cowplot yet.

**Comment by DominiqueMakowski** [comment]
I agree, patchwork looks great (but haven't tried it yet). Although switching to cowplot would be very easy as it supports "tags" (subfigure annotation A, B, C etc.), just need to replace with `cowplot::plot_grid(...)`

**Comment by strengejacke** [comment]
Yes, we don't need to make it more complicated than necessary.

**Comment by IndrajeetPatil** [comment]
This is no longer relevant since we are now using `{patchwork}` package here.
