### ISSUE TITLE
Long Term Goal: reduce dependencies, esp. dplyr

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#43]
I think this is doable, and also preferable. This is rather a slow process, with small steps.

**Comment by IndrajeetPatil** [comment]
Current non-`easystats` packages (except `ggplot2`) that will need to be removed from dependencies:

- [ ] dplyr
- [ ] ggridges
- [ ] magrittr
- [ ] rlang

**Comment by bwiernik** [comment]
What is the thinking on R version dependency?

**Comment by IndrajeetPatil** [comment]
There was a discussion about this here:
https://github.com/easystats/insight/issues/284

**Comment by bwiernik** [comment]
rlang isn't a problem--it's imported by ggplot and needed for the `.data` pronoun as far as I am aware.

**Comment by bwiernik** [comment]
ggridges is harder. The only package I'm aware of that provides similar functionality is ggdist, and that has a lot of tidyverse dependencies. ggridges is really only adding a dependency on plyr. Perhaps we could (1) submit a PR to ggridges to remove that and (2) move ggridges to suggests because it only applies to bayestestR methods currently?

**Comment by bwiernik** [comment]
https://github.com/wilkelab/ggridges/pull/71

**Comment by IndrajeetPatil** [comment]
> move ggridges to suggests because it only applies to bayestestR methods currently

Yes, I like this approach. This is what we are doing with other needed plotting packages (like `tidygraph`, e.g.) as well.

**Comment by bwiernik** [comment]
Okay, ggridges doesn't have any extra dependencies anymore either

**Comment by IndrajeetPatil** [comment]
Amazing!

![tenor](https://user-images.githubusercontent.com/11330453/118698226-6fd2b700-b810-11eb-832b-e5732e0ba95b.gif)
