### ISSUE TITLE
Option to add priors to posterior plots

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#48]
Now that priors can easily be extracted as distributions using `simulate_priors`, I wonder if it would be tough to give the option to add them in the posterior plots (so you can see for all parameters, the prior and the posterior)...

**Comment by strengejacke** [comment]
hm, doesn't `geom_ridgeline_gradient` an alpha option?

**Comment by strengejacke** [comment]
ok, `geom_ridgeline()` has, and I don't need geom_ridgeline_gradient() for the prior layer

**Comment by strengejacke** [comment]
It is probably better to add the prior layer onto the main layer for those plots where we have to use `geom_ridgeline_gradient`, because that geom allows no alpha.

**Comment by strengejacke** [comment]
I started adding the prior-feature to some of the plots:

https://easystats.github.io/see/articles/bayestestR.html

- Do we want the argument to be names `show_priors` or just `priors`?
- What about the other arguments, like `priors_alpha`?

In some cases we hard-code colors (e.g. point-estimate). We may think changing this somewhen in the future...

**Comment by mattansb** [comment]
>  Do we want the argument to be names show_priors or just priors?

Maybe `add_priors` ot `plot_priors`?
--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab <http://www.deverplab.com/>
Personal Website <https://sites.google.com/view/mattansb>

**Comment by DominiqueMakowski** [comment]
I like when args controlling a main arg stems out of it, so if we go for `priors_alpha` it makes sense to leave it just as `priors = TRUE`

**Comment by DominiqueMakowski** [comment]
![](https://media1.tenor.com/images/23189d456e0608040773536982af3b9b/tenor.gif)

**Comment by strengejacke** [comment]
I'm not sure whether there are any plots left to add priors? For HDI, we have the simple density plots, so I think we don't additionally need this option for HDI, do we?
