### ISSUE TITLE
for single posterior/distribution, use regular area instead of ridges

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#49]
``` r
library(see)
plot(bayestestR::hdi(rnorm(1000)))
```

![](https://i.imgur.com/7Tt509B.png)

<sup>Created on 2019-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Would be nice in these cases to have a regular distribution area (that touches the x axis). That would affect all the bayestestR plotting so I am not sure which is the most convenient way of doing it

**Comment by strengejacke** [comment]
hm, which geom allows varying aes? geom_ribbon() and geom_area() don't allow varying fills.

**Comment by strengejacke** [comment]
Ok, found another solution...

**Comment by strengejacke** [comment]
I _think_ all cases are covered now.
