### ISSUE TITLE
Axis labels in README

### ISSUE THREAD

**Issue by pdwaggoner** [easystats/see#5]
@DominiqueMakowski and @strengejacke the X axis labels in figures 1 and 2 under `Multiple Plots` in the `README` look a bit off. Not sure where these are stored (presumably they are png or eps files...). Could be worth a look to correct for interested users.

**Comment by DominiqueMakowski** [comment]
Yes, I planned to rotate them but... you wanna give it a try 😄 ? The code for generating the readme is [there](https://github.com/easystats/see/blob/master/README.md). Feel free to modify and commit!

**Comment by strengejacke** [comment]
https://github.com/strengejacke/sjPlot/blob/master/R/sjplot_themes.R#L201

**Comment by strengejacke** [comment]
> Yes, I planned to rotate them but... you wanna give it a try 😄 ? The code for generating the readme is [there](https://github.com/easystats/see/blob/master/README.md). Feel free to modify and commit!

Isn't the code in the _rmd_ file, not md?
https://github.com/easystats/see/blob/master/README.Rmd

**Comment by DominiqueMakowski** [comment]
Yes, the Rmd file my mistake. @strengejacke what does the sjplot function do? Does it rotate the labels automatically if overlapping?

**Comment by strengejacke** [comment]
No, not automatically. I'm not sure, but I guess automatic label rotation based on potential overlapping might be difficult to achieve, maybe the ggrepel-package gives some inspiration here.

**Comment by pdwaggoner** [comment]
I am happy to fix it. The solution might be pretty simple, if we just include `+ theme(axis.text.x  = element_text(angle=45, vjust=0.5, size=9))` . Baking this into the source code would just make all axis labels angled at 45 degrees (or whatever we set it as). So it would kind of be automatic? Not sure, but it could be a good stop gap fix. If you guys like this solution at least for the `README`, let me know and I would be happy to fix it quickly there.

**Comment by DominiqueMakowski** [comment]
For the README, we can go ahead and rotate by 45°. However, I am not sure this should be hardcoded within the theme_modern function (although an argument to do so would be handy).

Nevertheless, yes a "true" automatic solution, similar to what ggrepel does, would be great, but I am not sure it is easily doable. This could be a potential feature for someday in the future :)

**Comment by pdwaggoner** [comment]
Cool - I just created the pull request. Feel free to merge when/if you'd like! 

Also, for a possible solution, we could just add a new logical argument in the `theme_modern()` function to allow users to rotate x axis labels or not. Something like:

```{R}
## Note the change in the function call as well as in the code at the end of the function:

theme_modern <- function(plot.title.size=15, plot.title.face="plain", plot.title.space=20, legend.position = "right", axis.title.space = 20, legend.title.size = 13, legend.text.size = 12, axis.title.size = 13, axis.title.face = "plain", axis.text.size = 12, tags.size=15, tags.face="bold", rotate=TRUE) {
  
  
  # Remove legend title if necessary
  if (is.null(plot.title.size)) {
    plot.title.size <- element_text(size = plot.title.size, face = plot.title.face, margin=margin(0,0,plot.title.space,0))
  } else if (plot.title.size == "none") {
    plot.title.size <- element_blank()
  } else {
    plot.title.size <- element_text(size = plot.title.size, face = plot.title.face, margin=margin(0,0,plot.title.space,0))
  }
  
  # Remove legend title if necessary
  if (is.null(legend.title.size)) {
    legend.title.size <- element_text(size = legend.title.size)
  } else if (legend.title.size == "none") {
    legend.title.size <- element_blank()
  } else {
    legend.title.size <- element_text(size = legend.title.size)
  }
  
  # Remove axis title if necessary
  if (is.null(axis.title.size)) {
    axis.title.size <- element_text(size = axis.title.size, face = axis.title.face)
  } else if (axis.title.size == "none") {
    axis.title.size <- element_blank()
  } else {
    axis.title.size <- element_text(size = axis.title.size, face = axis.title.face)
  }
  
  # Remove axis text if necessary
  if (is.null(axis.text.size)) {
    axis.text.size <- element_text(size = axis.text.size)
  } else if (axis.text.size == "none") {
    axis.text.size <- element_blank()
  } else {
    axis.text.size <- element_text(size = axis.text.size)
  }
  
  # rotate x axis labels or not?
  if (rotate == TRUE) {
    axis.text.x <- element_text(angle=45, vjust=0.5, size=9)
  } else {
    axis.text.x <- element_text(angle=0, vjust=0.5, size=9)
  }
  
  theme_classic() +
    theme(
      plot.title = plot.title.size,
      legend.position = legend.position,
      legend.text = element_text(size = legend.text.size),
      legend.title = legend.title.size,
      legend.key = element_blank(),
      legend.spacing.x = unit(2, "pt"),
      axis.title = axis.title.size,
      axis.title.y = element_text(margin = margin(t = 0, r = axis.title.space, b = 0, l = 0)),
      axis.title.x = element_text(margin = margin(t = axis.title.space, r = 0, b = 0, l = 0)),
      axis.text = axis.text.size,
      axis.ticks = element_blank(),
      plot.tag = element_text(size = tags.size, face = tags.face),
      strip.background = element_blank(),
      strip.text = element_text(face="bold"),
      axis.text.x = axis.text.x
    )
}


## WORKING EXAMPLE
library(ggplot2)

p1.rotated.default <- ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) + 
  geom_boxplot() + theme_modern() 
p1.rotated.default

p2.not.rotated <- ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) + 
  geom_boxplot() + theme_modern(rotate=FALSE) 
p2.not.rotated
```

**Comment by pdwaggoner** [comment]
I am going to start a new issue for workshopping an update to the `see` package for my proposed axis label rotating option. Stand by...
