### ISSUE TITLE
CRAN 0.3.0

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#53]
See https://github.com/easystats/see/projects/3

**Comment by strengejacke** [comment]
@DominiqueMakowski ok, I think this package is ready for release... It just needs _effectsize_ to be on CRAN to close https://github.com/easystats/see/pull/51, then we have a good update for submission, I'd say.

**Comment by strengejacke** [comment]
@DominiqueMakowski Can you please take a closer look at the plots here:

https://easystats.github.io/see/articles/bayestestR.html
https://easystats.github.io/see/articles/parameters.html

And give feedback on plot-annotations (legends etc.), in particular for p_significance and principal_components?

**Comment by DominiqueMakowski** [comment]
I love it!!!

**Comment by strengejacke** [comment]
I'm just a bit uncertain about the legend here:
https://easystats.github.io/see/articles/bayestestR.html#adding-prior-samples-2 

;-)

If you have any better terms, let me know...

**Comment by DominiqueMakowski** [comment]
Ah right, I'd remove the legend title, and then maybe rename "less probable" to... well I actually don't know, can we live it empty?

**Comment by strengejacke** [comment]
Still got no good idea for naming the legend of the practical significance function (see https://easystats.github.io/see/articles/bayestestR.html#adding-prior-samples-2). @mattansb any idea? Or somebody else?

**Comment by mattansb** [comment]
I don't like the "less probable" one - both sides mark practically significant values... But I don't have any better ideas.....

**Comment by strengejacke** [comment]
Ok, I did some "major revisions" to the package, rewriting and redesigning many plot-functions, with two aims in mind: 1) constistent outputs accross different plots and models; 2) standardize code chunks.

We now have repeating code in a lot of placed inside the plot-functions, which might be refactored in the future (moving to own functions). By this, we can step by step remove duplicated code to make it more readable and maintainable.

But my request to you is now to carefully check all the plots in the vignettes:
https://easystats.github.io/see/

Note that label names "differ" depending on the column-layout. When needed, random/zi parts are indicated attached to the parameter names, else not. Same for facet headings. I tried to make plot annotations more "human readable". In the end, we can even think of further "cleaning" like we do in `model_parameters()`, but that's not important for the next CRAN submission...

**Comment by DominiqueMakowski** [comment]
It looks awesome, great job! (I am rediscovering some of the plots, for e.g. for performance, which are 😍). I have given it a brief look, everything seems 👌 👌

**Comment by mattansb** [comment]
Looks awesome!

**Comment by strengejacke** [comment]
on CRAN.
