### ISSUE TITLE
ncol, ncols, n_cols or n_columns?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/see#58]
Currently in `plots()` we use `ncol`, but in plot.bayestestR_hdi we use `n_columns`. We might wanna harmonize this. For what it's worth, I think ncol and nrow are the most commonly used in R.

**Comment by DominiqueMakowski** [comment]
However, since we have `n_pies`, I also like `n_cols` and `n_rows`

**Comment by strengejacke** [comment]
wie could use `n_cols`, however, I always had the feeling you prefered "real" words like "columns" instead of "cols" :-)

**Comment by DominiqueMakowski** [comment]
I do I do in general, but in this case I find "cols" okay 🙆‍♂

**Comment by strengejacke** [comment]
![Download](https://user-images.githubusercontent.com/26301769/70033787-75065c80-15b0-11ea-8ed4-9e4563e36549.png)

**Comment by strengejacke** [comment]
![3i8x80](https://user-images.githubusercontent.com/26301769/70033910-af6ff980-15b0-11ea-9acb-82283e94f8a1.jpg)

**Comment by DominiqueMakowski** [comment]
I mean cols is sort of a convention in programming (even Julia, which tries to really make the right decisions in terms of naming and design, uses `cols` soooo)

**Comment by strengejacke** [comment]
> which tries to really make the right decisions in terms of naming

But obviously failed in this case. ;-)

**Comment by DominiqueMakowski** [comment]
I am also okay with n_columns tho, as long as it's consistent (-> we need to change it in `plots()`) 😁
