### ISSUE TITLE
[Feature request] support for 'nls' models

### ISSUE THREAD

**Issue by fmmattioni** [easystats/see#66]
I was wondering if there are any plans to support `nls` models too?

I am mainly interested in features like those described in [this vignette](https://easystats.github.io/see/articles/performance.html).

**Comment by strengejacke** [comment]
Duplicate (and funnily, same issue number) of https://github.com/easystats/insight/issues/66.

**Comment by fmmattioni** [comment]
Oh, I am so sorry, I even searched for 'nls'  in the issues here but couldn't find anything. I will see if I can somehow contribute to the discussion there.
