### ISSUE TITLE
Color scales and palettes

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#70]
@mattansb @DominiqueMakowski @IndrajeetPatil 

I have added new color scales and pre-defined palettes, and I tweaked existing palettes a bit in the see package. See some examples here: https://easystats.github.io/see/articles/seecolorscales.html

Suggestions? Comments? Satisfied?

**Comment by strengejacke** [comment]
I have added an explicit `"light"` palette to the color scales for the dark themes, and added a related vignette. Here are the vignettes for the "normal" scales:
https://easystats.github.io/see/articles/seecolorscales.html

and here for the dark themes:
https://easystats.github.io/see/articles/seecolorscalesdark.html

Furthermore, more plotting functions now use the own see-color scales (like `scale_color_flat()`) instead of default ggplot.

Page is currently building, so it may take a minute until the links work.

**Comment by DominiqueMakowski** [comment]
Looking absolutely gorgeous (and the documentation is 👌)

**Comment by strengejacke** [comment]
Ok, now both links should work, so you can also see the vignette on dark themes, and the new defaults ([bayestestR](https://easystats.github.io/see/articles/bayestestR.html), [parameters](https://easystats.github.io/see/articles/parameters.html#cluster-analysis-1)).

**Comment by mattansb** [comment]
Looks awesome (:
--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab <http://www.deverplab.com/>
Personal Website <https://sites.google.com/view/mattansb>
