### ISSUE TITLE
plot() for bayestestR::estimate_density()

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#74]
@DominiqueMakowski @mattansb 
I've slightly revised the plot-method, so it also shows point estimate and CI. And the contour line is now removed. Comments?

https://easystats.github.io/see/articles/bayestestR.html#density-estimation-1

**Comment by mattansb** [comment]
I don't remember what this looked like before - but it (also?) looks good (even better?) now (:

**Comment by strengejacke** [comment]
This is the new version:

![](https://easystats.github.io/see/articles/bayestestR_files/figure-html/unnamed-chunk-5-1.png)


And this the old version

![image](https://user-images.githubusercontent.com/26301769/90369108-71960100-e06b-11ea-8272-fdb78aea3eac.png)

**Comment by DominiqueMakowski** [comment]
awesome, though this blue color is a bit too *SJVERSY* for me but hey 😁😁

**Comment by strengejacke** [comment]
> though this blue color is a bit too _SJVERSY_ for me but hey 😁😁

that was not intentional ;-)
It's one of our see-color-palettes: https://github.com/easystats/see/blob/master/R/plot.estimate_density.R#L145
Feel free to choose/suggest a different color.

**Comment by strengejacke** [comment]
```r
plot(result, stack = FALSE) + 
  ggplot2::scale_color_manual(values = unname(social_colors("grey"))) + 
  ggplot2::scale_fill_manual(values = unname(social_colors("grey")))
```

![image](https://user-images.githubusercontent.com/26301769/90378665-eb34eb80-e079-11ea-9894-5dde911696d3.png)
