### ISSUE TITLE
More descriptive name for geom_point2()

### ISSUE THREAD

**Issue by bwiernik** [easystats/see#75]
The name `geom_point2()` isn't very descriptive about the function does. Do you think you could add a more descriptive alias, such as `geom_point_borderless()`?

**Comment by DominiqueMakowski** [comment]
that seems reasonable to me, @strengejacke what do you think?

**Comment by strengejacke** [comment]
yes, but naming is not my expertise.

**Comment by bwiernik** [comment]
The difference is that there is no line on point2, right?

**Comment by DominiqueMakowski** [comment]
> The difference is that there is no line on point2, right?

Yes that's correct. @bwiernik would you like to make a PR to add this as an alias?

**Comment by bwiernik** [comment]
In the README, the geoms are described as:

> geom_points2() and geom_jitter2() allow points without borders and contour.

What does "contour" mean here?

**Comment by strengejacke** [comment]
I think it's used synonymous here.

**Comment by DominiqueMakowski** [comment]
Yes, though it would be better indeed to pick one of "borders", "contour" or "outline". I wonder which one is the most used in English / in the ggplot context

**Comment by bwiernik** [comment]
In the linked PR, I updated the description to say "outline stroke (border, contour)". "stroke" is the actual term used by ggplot2. I think the parenthetical note makes it clearer that these are intended to be synonyms.
