### ISSUE TITLE
pgdown action fails

### ISSUE THREAD

**Issue by strengejacke** [easystats/see#78]
https://github.com/easystats/see/runs/1149265534

If anybody knows why, let me know...

**Comment by strengejacke** [comment]
The concrete error seems to be:

```
Quitting from lines 51-71 (performance.Rmd) 
Error in value[[3L]](cond) : 
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)
--------------------------------------------------------------------------------
##[error]Error: Failed to render RMarkdown
Backtrace:
    █
 1. └─pkgdown::deploy_to_branch(new_process = FALSE)
 2.   └─pkgdown::build_site(...)
 3.     └─pkgdown:::build_site_local(...)
 4.       └─pkgdown::build_articles(...)
 5.         └─purrr::walk(...)
 6.           └─purrr::map(.x, .f, ...)
 7.             └─pkgdown:::.f(.x[[i]], ...)
 8.               └─pkgdown:::render_rmarkdown(...)
<parent: error/callr_status_error>
Backtrace:
```

**Comment by strengejacke** [comment]
@mattansb @DominiqueMakowski @IndrajeetPatil any ideas?

**Comment by mattansb** [comment]
Do these lines run locally?

https://github.com/easystats/see/blob/9fed4bd49621f9fc7623e01441f286cb05828433/vignettes/performance.Rmd#L50-L71

**Comment by strengejacke** [comment]
Yes, for me it runs locally. And the vignette rendered well for a long time, and there was no suspicious change in _performance_ that I can recall which may result in this error.

**Comment by strengejacke** [comment]
Looks (I hope so) we're getting closer to the source of this error.

According to [this example](https://github.com/easystats/effectsize/issues/135#issuecomment-698137482), the same error `Warning in value[[3L]](cond)` occurs for classical ZI-models.

```r
library(pscl)
#> Classes and Methods for R developed in the
#> Political Science Computational Laboratory
#> Department of Political Science
#> Stanford University
#> Simon Jackman
#> hurdle and zeroinfl functions by Achim Zeileis

data("bioChemists")
m <- zeroinfl(art ~ fem + mar * exp(kid5) + ment | kid5 + phd, data = bioChemists)
#> Warning in value[[3L]](cond): system is computationally singular: reciprocal
#> condition number = 1.40243e-18FALSE
```

In the pkgdown example, it's also a ZI-model (from glmmTMB) that leads to this warning/error:

![image](https://user-images.githubusercontent.com/26301769/94121121-41533680-fe51-11ea-8e3a-0cc3b5cdb325.png)

The reason might be a matrix-problem:

https://stackoverflow.com/questions/50928796/system-is-computationally-singular-reciprocal-condition-number-in-r/50929000#50929000

However, not sure why this suddenly occurs?

Guess:

1. A package has changed, and now this gives an error (maybe Matrix package, but that wasn't updated)
2. A change in the R-dev version that leads to this error.
3. ?

**Comment by IndrajeetPatil** [comment]
@strengejacke Can this be closed? `pkgdown` actions seems no longer to be failing.

**Comment by strengejacke** [comment]
Yes
