### ISSUE TITLE
Issue loading "sse" package

### ISSUE THREAD

**Issue by Kuroshiwo** [easystats/see#80]
Error was thrown while loading "see" package running R under RStudio in Windows OS 10. See error below:

> ##---------------------------- Visualise the Bayes factor ---------------------
> library(see)
Error: package or namespace load failed for ‘see’:
 object ‘to_table’ is not exported by 'namespace:insight'
> plot(bayesfactor(result)) +
+      scale_fill_pizza()

Error in plot.bayesfactor_models(bayesfactor(result)) : 
  Package 'see' needed to plot models' Bayes factors. Please install it by running `install.packages('see')`.

> ##---------------------------- Visualise the Bayes factor ---------------------
> install.packages("see")
Installing package into ‘C:/Users/richa/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/see_0.6.0.zip'
Content type 'application/zip' length 458958 bytes (448 KB)
downloaded 448 KB

package ‘see’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\richa\AppData\Local\Temp\RtmpmwDTZX\downloaded_packages

> library(see)
Error: package or namespace load failed for ‘see’:
 object ‘to_table’ is not exported by 'namespace:insight'

**Comment by strengejacke** [comment]
We added some new functions for markdown-tables, and the API changed in the last GitHub versions. But now the API is stable, so you would need to manually re-install to resolve your issue:

1. install insight 0.11.0 from CRAN
2. install the packages parameters, correlation and performance from GitHub (one by one).

That should work.
