### ISSUE TITLE
geom_halfviolin and geom_violindot should allow quantile lines to be drawn

### ISSUE THREAD

**Issue by mrkaye97** [easystats/see#82]
[`ggplot2::geom_violin()`](https://ggplot2.tidyverse.org/reference/geom_violin.html) has a `draw_quantiles = NULL` argument, in which a user can specify a list of quantiles to draw, i.e. `draw_quantiles = c(.025, .5, .975)` for a median + 95% bands. This seems like a relatively easy one to implement (can probably just copy straight over from `ggplot2`) but I'm not 100% sure of that.

**Comment by strengejacke** [comment]
Maybe related to https://github.com/easystats/see/issues/68.

**Comment by IndrajeetPatil** [comment]
Closing in favor of #68
