### ISSUE TITLE
Improving check_model()

### ISSUE THREAD

**Issue by isabellaghement** [easystats/see#97]
Someone shared the diagnostic plots below on Twitter and several of us noticed that they look nice but need more appropriate labelling, as described below.  

![image](https://user-images.githubusercontent.com/57458528/111399234-2afc9980-8682-11eb-8b1f-6e13ee741801.png)

The Twitter thread is available here: 

https://twitter.com/CMastication/status/1371779205453778946

**VIF [Top Left]**  The *Correlation* label refers to whether the Variance Inflation Factor (VIF) is Low or High?  Why not state that by replacing *Correlation* with *VIF*?  The use of the word *Correlation* is a bit vague - we don't know if a predictor is highly correlated with just one other predictor, all other predictors, etc.   We also don't know what threshold is used to determine whether VIF is high or low.  If the legend title is changed to VIF, the legend labels could be listed as:  Low (VIF < 10) and High (VIF >= 10) or something like that (depending on what the threshold is). 

**QQ Plot [Top Right]**  Can this plot be titled *Check for Normality of Residuals*?  Can the subtitle of the plot be listed as *Dots should fall along the line."  Can the horizontal axis be labelled "Standard Normal Distribution Quantiles"? (Theoretical Quantiles does not indicate what theoretical distribution we are dealing with.) 

**Density Plot [Middle Left]**  Can this plot be titled *Check for Normality of Residuals*?  Here, there are two distributions being plotted - the distribution of the model residuals (blue filled density curve) and a reference Normal distribution (with the same mean and standard deviation as the distribution of model residuals?).  The two distributions should be clearly labelled so the user understands which is which.  The distribution of the model residuals should look like a normal curve *centered at zero".  

**Linear Relationship [Middle Right]**   If this plot will be used exclusively to check the assumption of linearity, then it should be labelled *Check for Linearity* or something to this effect.   If the assumption of linearity holds, this plot should reveal no systematic structure in the plotted observations.   In particular, the smooth red line should be (roughly) horizontal and pass through zero.  

**Homogeneity of Variance [Bottom Left]**  The blog post https://boostedml.com/2019/03/linear-regression-plots-scale-location-plot.html explains what people should look for when interpreting a scale-location plot:  1) The smooth red curve in this plot should be a (roughly) flat line parallel with the horizontal axis; 2) The spread of the observations depicted in this plot should be (roughly) constant along the red curve.  Also, should this plot be titled *Check for Homogeneity of Variance*?

** [Bottom Right]**  Does this plot shows the distribution of the Cook's distances associated with the regression observations?  If yes, than the plot makes it difficult to see which specific observations might be influential since the plot may lump together observations with large Cook's distances. (Even if such observations are not lumped together, we can't tell from the plot which observations are influential - we can just tell how many are influential, provided we use our own threshold for deciding when influence is large.) Why not replace this plot with a "spike plot" that shows the observation number on the horizontal axis and the corresponding value of Cook's distances on the vertical axis?  Having a threshold for judging large influence in such a plot would be helpful.  

https://boostedml.com/2019/03/linear-regression-plots-scale-location-plot.html

**Comment by strengejacke** [comment]
@bbolker 

> Add confidence intervals to both of these panels?

I'm not sure what best practice would be. Will geom_smooth() from ggplot2 be sufficient, or are those CI inaccurate for this purpose?

**Comment by bwiernik** [comment]
My major concern with these plots is that I think the titles are misleading. To me, they seem to suggest a one-to-one correspondence of assumption to plot. That’s often not the case. For example, the QQ plot can be really funky if there is unmodeled nonlinearity rather than a distributional problem per se. In such a case, I feel like the titles here will lead folks toward inappropriate remedies like transformations rather than adjusting the model specification. 

 My preference would be to replace the plot titles with their actual formal titles (scale-location, qq plot, etc) but keep the subtitles indicating what a “good” plot should look like.

**Comment by strengejacke** [comment]
That's a good point! I wonder whether this should be mentioned in the docs and/or a message is printed that states that checking model assumption do not necessarily show lack of fit. Thanks to @mattansb, there is now an option to add partial residuals to effect plots in _ggeffects_: https://strengejacke.github.io/ggeffects/articles/introduction_partial_residuals.html

That said, a better practice would be to look at both, checking model assumptions _and_ lack of fit, which indeed might be complementary steps / plots.

**Comment by strengejacke** [comment]
Current state:

``` r
library(performance)
m <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)
check_model(m)
#> Loading required namespace: qqplotr
```

![](https://i.imgur.com/PkSXxi0.png)

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by bwiernik** [comment]
One approach would be to change the plot titles and then add sections to the docs for each plot describing what it shows and potential causes of deviations from the expected appearance. Those could link to the effects plots questions.

**Comment by bwiernik** [comment]
For the top-right plot, it might be nicer to title the y axis:

```r
expression(sqrt(" | Std. residuals | "))
```

**Comment by IndrajeetPatil** [comment]
These are all great suggestions!

There is one panel which is **not** included in the output for `lm` object, and is only present for `merMod` object [outputs](https://easystats.github.io/see/articles/performance.html#overall-model-check-1).

Are there any additional suggestions for this panel?
(As @isabellaghement suggested, the line here should read something like `"Dots should fall along the line."`)

![image](https://user-images.githubusercontent.com/11330453/111612123-77102100-87dd-11eb-9708-b5be69869678.png)

**Comment by bwiernik** [comment]
Here is an example of what I was thinking regarding titles (using the base R 6 lm diagnostic plots):
![image](https://user-images.githubusercontent.com/4773225/111626462-6d2df400-87c4-11eb-97e5-a541943e251d.png)

Beyond the titles, a few other things I am wondering about:

1. Would it be valuable to label points with the largest influence values, as done in base R's plots?
2. In addition to or in lieu of the Cook's distance histogram, would it be better to show one of the 3 influence plots that base R provides (e.g., the Residuals vs Leverage plot is the default). Perhaps it would be better to move all 4 of these to the plot method for `check_outliers()`?
3. For the Cook's D histogram, perhaps adding an indication of the median for the F distribution as a reference value in the subtitle?
4. For the trend lines, histogram, qq plot, it would be good to specify the formula, number of bins, quiet the require message so that the messages don't print.

**Comment by bwiernik** [comment]
Another question: De-trended qq plots (["worm plots"](https://www.tjmahr.com/quantile-quantile-plots-from-scratch/)) might be easier to interpret. Perhaps it might be worthwhile to do that with the residuals and random effects plots?

**Comment by mattansb** [comment]
> Another question: De-trended qq plots ("worm plots") might be easier to interpret. Perhaps it might be worthwhile to do that with the residuals and random effects plots?

Done!

``` r
m <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)

performance::check_model(m)
#> Registered S3 method overwritten by 'parameters':
#>   method     from      
#>   ci.blavaan bayestestR
#> Loading required namespace: qqplotr
```

![](https://i.imgur.com/PtL4bLl.png)

``` r
performance::check_model(m, detrend = TRUE)
```

![](https://i.imgur.com/jq22p07.png)

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
- For collinearity: 
  - [ ] I'd add back the legend to be put on the side (but with no title, just like the colors and the labels), 
  - [ ] I'd change the title to: "High bars might indicate potential collinearity issue" or something along those lines 
  - [ ] add "Variance Inflation Factor (VIF)" as a y axis
- For the outliers plot: 
  - [ ] Rename the title as "Influential Observations" 
  - [ ] Add a subtitles for consistency "High Cook's distance might reflect potential outliers"
  - [ ] It's true that the distributional format is a bit confusing at first, maybe it would be more straightforward to have as it was suggested all observations as x axis and then thin lollipops indicating the distance as y value. So that in a glance, one could see where the saliently high lollipops are located (i.e., approximately which row number is it).

**Comment by bwiernik** [comment]
> I'd add back the legend to be put on the side (but with no title, just like the colors and the labels),

To keep the plots aligned, maybe horizontal on the bottom.

**Comment by strengejacke** [comment]
![Rplot](https://user-images.githubusercontent.com/26301769/112196687-90fd9980-8c0b-11eb-92c7-663be661c279.png)

**Comment by isabellaghement** [comment]
This looks much improved.  The **Influential Observations** plot needs some work - the current plot essentially answers the question _"How many influential observations are there - if any - in this model?"_.  But usually we want to identify those observations so we can examine them one by one or as a group. Knowing how many there are is not as helpful as knowing what they are!

If possible, I would suggest replacing the  **Influential Observations** plot with one of these plots: 

1.  A spike plot where the x-axis shows the observation number and the y-axis shows the influence of each observation (a threshold for judging influence can be added via a horizontal line); 

2.  A plot similar to what **influencePlot()** in the **car** package produces:

 ```
library(car)
influencePlot(lm(prestige ~ income + education, data=Duncan),  id=list(method="identify"))
```

**Comment by strengejacke** [comment]
For

```r
plot(check_outliers(model))
```

we have such a plot, but for larger data sets, in particular if the plot is just a small panel as in `check_model()`, this become pretty useless:

``` r
library(performance)
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
data(efc)
efc <- sjmisc::to_factor(efc, c161sex, e42dep, c172code)
m <- lm(neg_c_7 ~ pos_v_4 + c12hour + e42dep + c172code, data = efc)
plot(check_outliers(m))
```

![](https://i.imgur.com/uRho2jX.png)

<sup>Created on 2021-03-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

That's the reason why we decided to just plot the amount of influential observations, as a quick glance, and then users may proceed to other diagnostic tools for outliers. I'm open to change that plot, but have no good idea how (in particular, since I rarely use those plots).

**Comment by bwiernik** [comment]
> 2. A plot similar to what influencePlot() in the car package produces:

This is essentially plot 5 in the base plot.lm() method. 

```r
library(car)
plot(lm(prestige ~ income + education, data=Duncan), which = 5)
```

The major difference is that in `influencePlot()`, Cook's distance is indicated by point area whereas in the base plot, it's indicated using contour lines. In my teaching experience, students find the contour lines helpful--if all of the points are inside the contours, there aren't any even somewhat influential points. (`influencePlot()` also uses studentized residuals versus standardized)

Compared to the base R plot that sets the contours at constant values of D = .5 and 1.0 (or the `influencePlot()` approach based on sample-based residual and leverage thresholds), perhaps a better idea would be to plot a contour based on the median of the F distribution used in `check_outliers()`

Here is some basic ggplot code for such a plot:
<details>
  <summary>check_influence() plot function</summary>

```r
check_influence <- function(
	model,
	na.rm = TRUE,
	cook.levels = NULL,
	base.theme = theme_minimal(),
	label.n = 3,
	ref.color = "darkgray",
	ref.linetype = "dashed",
	smooth.color = "blue",
	resid.type = c("pearson", "response"),
	se = FALSE,
	span = .6,
	detrend = TRUE) {
	if (!inherits(model, "lm")) {
		stop("Only \"lm\" models are currently supported.")
	}
	if (inherits(model, "rlm")) {
		stop("\"rlm\" models not currently supported.")
	}
	if (inherits(model, "glm")) {
		stop("\"glm\" models not currently supported.")
		resid.type <- "pearson"
	}
	
	summ <- summary(m)
	cook.threshold <-
		round(qf(.5, summ$fstatistic[2], summ$fstatistic[3]), 2)
	cook.levels <- c(cook.threshold, cook.levels)
	label.n <- as.integer(label.n)
	caption <- paste("Model:", deparse(formula(model)))
	plot_data <-
		tibble::rownames_to_column(fortify(model), var = ".name")
	base <- ggplot(plot_data) + base.theme +
		theme(
			plot.title.position = "plot",
			plot.subtitle = ggtext::element_markdown(size = 10)
		)
	
	p5 <- base +
		aes(.hat, .stdresid) +
		geom_point(na.rm = na.rm) +
		stat_smooth(
			formula = y ~ x,
			method = "loess",
			na.rm = na.rm,
			se = se,
			span = span,
			color = smooth.color
		) +
		geom_vline(
			xintercept = 0,
			color = ref.color,
			linetype = ref.linetype) +
		geom_hline(
			yintercept = 0,
			color = ref.color,
			linetype = ref.linetype) +
		labs(
			x = expression("Leverage (" * h[ii] * ")"),
			y = "Std. residuals",
			title = "Residuals vs leverage",
			subtitle = paste0("*Check for influential values, Cook's D > ", cook.threshold, "*")
		) +
		theme(legend.position = "bottom") +
		ggrepel::geom_text_repel(
			data = dplyr::slice_max(plot_data, abs(.cooksd), n = label.n),
			aes(label = .name),
			size = 2
		)
	
	if (length(cook.levels)) {
		p <- model$rank
		.hat <- sort(plot_data$.hat)
		.cook_ref <-
			lapply(cook.levels,
						 function (crit)
						 	sqrt(crit * p * (1 - .hat) / .hat))
		.hat80 <- min(.hat) + diff(range(.hat)) * .8
		.cook_labels <- c("Cook's D = ", rep("", length(cook.levels) - 1))
		.cook_lines <-
			c(
				lapply(
					1:length(cook.levels),
					function(.level)
						annotate(
							geom = "line",
							x = .hat,
							y = .cook_ref[[.level]],
							color = ref.color,
							linetype = ref.linetype
						)),
				lapply(
					1:length(cook.levels),
					function(.level)
						annotate(
							geom = "line",
							x = .hat,
							y = -1 * .cook_ref[[.level]],
							color = ref.color,
							linetype = ref.linetype
						)),
				lapply(
					1:length(cook.levels),
					function(.level)
						annotate(
							geom = "label",
							label = paste(
								.cook_labels[.level],
								formatC(cook.levels[.level],
												digits = 1,
												format = "f")
							),
							x = .hat80,
							y = sqrt(cook.levels[.level] * p * (1 - .hat80) / .hat80),
							hjust = "right",
							color = colorspace::darken(ref.color, amount = .4),
							label.size = 0,
							fill = NA,
							size = 3
						)),
				lapply(
					1:length(cook.levels),
					function(.level)
						annotate(
							geom = "label",
							label = formatC(cook.levels[.level],
															digits = 1,
															format = "f"),
							x = -.01 + .hat80,
							y = -1 * sqrt(cook.levels[.level] * p * (1 - .hat80) / .hat80),
							color = colorspace::darken(ref.color, amount = .4),
							hjust = "right",
							label.size = 0,
							fill = NA,
							size = 3
						))
			)
		p5 <- p5 +
			.cook_lines +
			coord_cartesian(ylim = extendrange(r = range(plot_data$.stdresid),
																				 f = 0.1))
	}
	
	out <- p5
	attr(out, "caption") <- caption
	return(out)
}
```
</details>

**Comment by bwiernik** [comment]
Using the function above:

```r
library(ggplot2)
library(performance)
library(sjPlot)
#> Learn more about sjPlot with 'browseVignettes("sjPlot")'.
data(efc)
efc <- sjmisc::to_factor(efc, c161sex, e42dep, c172code)
m <- lm(neg_c_7 ~ pos_v_4 + c12hour + e42dep + c172code, data = efc)
check_influence(m)
check_influence(m, cook.levels = c(.1, .5, 1))
```

![image](https://user-images.githubusercontent.com/4773225/112213382-6522e980-8bf4-11eb-827a-99a4edf72c65.png)

![image](https://user-images.githubusercontent.com/4773225/112213647-b03cfc80-8bf4-11eb-9ea0-5024568f893f.png)

**Comment by bwiernik** [comment]
I think the top one nicely shows that there aren't any particularly influential values because everything is inside the F-median contour. The second plot is shown just to illustrate what a contour looks like.

**Comment by strengejacke** [comment]
The second plot looks nice, I think we could use that one. Is there any "copyright" on that code, or can we use it and add you as contributor to the pkg or anything in that direction, @bwiernik? We could name that plot "influential observations", and subtitlte could be "dots should be inside contour lines" or something like that.

**Comment by bwiernik** [comment]
Here is a somewhat better version that doesn't zoom in on the points (ensures the `qf(.50, p, n - p)` contour always shows).

<details>
  <summary>check_influence() plot function</summary>

```r
check_influence <- function(
	model,
	na.rm = TRUE,
	cook.levels = NULL,
	base.theme = theme_minimal(),
	label.n = 3,
	ref.color = "darkgray",
	ref.linetype = "dashed",
	smooth.color = "blue",
	resid.type = c("pearson", "response"),
	se = FALSE,
	span = .6,
	detrend = TRUE) {
	if (!inherits(model, "lm")) {
		stop("Only \"lm\" models are currently supported.")
	}
	if (inherits(model, "rlm")) {
		stop("\"rlm\" models not currently supported.")
	}
	if (inherits(model, "glm")) {
		stop("\"glm\" models not currently supported.")
		resid.type <- "pearson"
	}
	
	summ <- summary(m)
	if (is.null(cook.levels) | !is.numeric(cook.levels)) {
		cook.levels <- round(qf(.5, summ$fstatistic[2], summ$fstatistic[3]), 2)
	}
	label.n <- as.integer(label.n)
	caption <- paste("Model:", deparse(formula(model)))
	plot_data <-
		tibble::rownames_to_column(fortify(model), var = ".name")
	base <- ggplot(plot_data) + base.theme +
		theme(
			plot.title.position = "plot",
			plot.subtitle = ggtext::element_markdown(size = 10)
		)
	
	p5 <- base +
		aes(.hat, .stdresid) +
		geom_point(na.rm = na.rm) +
		stat_smooth(
			formula = y ~ x,
			method = "loess",
			na.rm = na.rm,
			se = se,
			span = span,
			color = smooth.color
		) +
		geom_vline(
			xintercept = 0,
			color = ref.color,
			linetype = ref.linetype) +
		geom_hline(
			yintercept = 0,
			color = ref.color,
			linetype = ref.linetype) +
		labs(
			x = expression("Leverage (" * h[ii] * ")"),
			y = "Std. residuals",
			title = "Check for influetial values",
			subtitle = "*Points should be inside the contour lines*"
		) +
		theme(legend.position = "bottom") +
		ggrepel::geom_text_repel(
			data = dplyr::slice_max(plot_data, abs(.cooksd), n = label.n),
			aes(label = .name),
			size = 2
		)
	
	if (length(cook.levels)) {
		p <- model$rank
		.hat <- sort(plot_data$.hat)
		.cook_ref <-
			lapply(cook.levels,
						 function (crit)
						 	sqrt(crit * p * (1 - .hat) / .hat))
		.hat80 <- min(.hat) + diff(range(.hat)) * .8
		.cook_labels <- c("Cook's D = ", rep("", length(cook.levels) - 1))
		.cook_lines <-
			c(
				lapply(
					1:length(cook.levels),
					function(.level)
						annotate(
							geom = "line",
							x = .hat,
							y = .cook_ref[[.level]],
							color = ref.color,
							linetype = ref.linetype
						)),
				lapply(
					1:length(cook.levels),
					function(.level)
						annotate(
							geom = "line",
							x = .hat,
							y = -1 * .cook_ref[[.level]],
							color = ref.color,
							linetype = ref.linetype
						)),
				lapply(
					1:length(cook.levels),
					function(.level)
						annotate(
							geom = ggrepel::GeomLabelRepel,
							label = paste(
								.cook_labels[.level],
								formatC(cook.levels[.level],
												digits = 1,
												format = "f")
							),
							x = .hat80,
							y = sqrt(cook.levels[.level] * p * (1 - .hat80) / .hat80),
							hjust = "right",
							color = colorspace::darken(ref.color, amount = .4),
							label.size = 0,
							fill = NA,
							size = 3
						)),
				lapply(
					1:length(cook.levels),
					function(.level)
						annotate(
							geom = ggrepel::GeomLabelRepel,
							label = paste(
								.cook_labels[.level],
								formatC(cook.levels[.level],
												digits = 1,
												format = "f")
							),
							x = .hat80,
							y = -1 * sqrt(cook.levels[.level] * p * (1 - .hat80) / .hat80),
							color = colorspace::darken(ref.color, amount = .4),
							hjust = "right",
							label.size = 0,
							fill = NA,
							size = 3
						))
			)
		p5 <- p5 +
			.cook_lines
	}
	
	out <- p5
	attr(out, "caption") <- caption
	return(out)
}
```

</details>

![image](https://user-images.githubusercontent.com/4773225/112228839-4d556080-8c08-11eb-80d8-5dd367b44c8d.png)

I'm happy for this code to be used/adapted and be credited as a contributor.

**Comment by DominiqueMakowski** [comment]
Great improvements thanks @strengejacke and @bwiernik! The only thing I wonder is for the VIF plot:

![image](https://user-images.githubusercontent.com/8875533/112234476-92fd4200-8c77-11eb-9e66-9b1e17164b80.png)


Should we always, in the legend, show the 3 possible outcomes (green, orange and red)? Even if they don't appear in the plot? On the one hand it's good if you have say only green bars, you clearly see that you don't have red and oranges (it makes its appraisal more absolute than relative). On the other hand, I suppose it could be confusing for some people (?) - like "where are the red / oranges bars since they appear in the legend?? Are the colour ink-cartridge empty in the Rstudio printing backend?" 😬 

What do you think?

**Comment by bbolker** [comment]
small point here, could the VIF plot have a dichromat-friendlier colour scheme? (I know green/orange/red has a useful cultural association with OK/questionable/dangerous, but ...) Could have the hues also associated with a difference in luminosity so they can still be distinguished?

**Comment by bbolker** [comment]
> @bbolker
> 
> > Add confidence intervals to both of these panels?
> 
> I'm not sure what best practice would be. Will geom_smooth() from ggplot2 be sufficient, or are those CI inaccurate for this purpose?

Very late reply, but I would think the `geom_smooth()` CI would be fine. The point is to give a general sense of the expected amount of variation in a sample of a given size, not to get some coverage probability exactly right.

**Comment by DominiqueMakowski** [comment]
> small point here, could the VIF plot have a dichromat-friendlier colour scheme?

Sure! do you have any example of know of any good resource that we could use to find more appropriate colours?

**Comment by DominiqueMakowski** [comment]
> I'm not sure what best practice would be. Will geom_smooth() from ggplot2 be sufficient


https://github.com/easystats/see/blob/8f0840ed87b67805b42abd6f3c2f45a2999595ba/R/print.check_model.R#L239-L244

Currently we use 'loess' it seems but it can be slow for large number of observations (ggplot's default behaviour of geom_smooth is to switch to "method=gam" above a certain n threshold). Should we directly use `method="gam"`? Besides being more scalable, the smooth line would be less woobly I think, and possibly better reflect the underlying process (?)

**Comment by bwiernik** [comment]
> Sure! do you have any example of know of any good resource that we could use to find more appropriate colours?

I’m strongly red-blind (protanopia). A blue-orange scheme generally works well. The magma palette in scale_color_viridis could be a good option.

**Comment by bwiernik** [comment]
> Should we always, in the legend, show the 3 possible outcomes (green, orange and red)? Even if they don't appear in the plot? 

yes, being consistent would be good

**Comment by strengejacke** [comment]
@bwiernik is Cook's D > .91 a well established threshold for influential observations?

**Comment by strengejacke** [comment]
> @bwiernik is Cook's D > .91 a well established threshold for influential observations?

Got it, it's based on the model's F-statistic.

**Comment by strengejacke** [comment]
![Rplot](https://user-images.githubusercontent.com/26301769/112278447-212af580-8c83-11eb-99fd-4233ee4613c6.png)

@bwiernik Could you please open a PR and add yourself as contributor to the DESCRIPTION file, if you like?

**Comment by strengejacke** [comment]
Here is the current state. @bbolker not sure which colors might be best for the VIF plot, I now chose color-brewer "Paired" palette.

![Rplot01](https://user-images.githubusercontent.com/26301769/112288852-0d38c100-8c8e-11eb-8c0c-c416c25d1ce3.png)

![Rplot02](https://user-images.githubusercontent.com/26301769/112288861-0f9b1b00-8c8e-11eb-9151-eccf65e8ee3c.png)

**Comment by mattansb** [comment]
For vif, maybe instead of kor in addition to) colors we can have horizonal lines with labels marking the thresholds? Just a thought...

**Comment by DominiqueMakowski** [comment]
> we can have horizonal lines with labels marking the thresholds? Just a thought...

This way we the minimum y axis will be "fixed" (since there would be a line at the high threshold) and we can have only "low" "moderate" and "high" in the legend (with colors matching the 3 horizotnal lines)

One final thought is to add "Density" (or "Distribution") as a ylabel in the normality of residuals last plot, so that all the vertical axes are aligned.

My god so much work has been put in this plot once it's *done* Daniel will be like "I NEVER want to see it again 🤮" 😅

**Comment by mattansb** [comment]
The axes will align when we switch to patchwork... (;

**Comment by strengejacke** [comment]
```r
lm(mpg ~ wt + am + gear + vs * cyl, data = mtcars)
```

![Rplot03](https://user-images.githubusercontent.com/26301769/112294275-26903c00-8c93-11eb-8767-3e58254b57cf.png)

```r
lm(neg_c_7 ~ pos_v_4 + c12hour + e42dep + c172code, data = efc)
```

![Rplot04](https://user-images.githubusercontent.com/26301769/112294495-327bfe00-8c93-11eb-8646-0ceb01b60e4f.png)

**Comment by strengejacke** [comment]
_(FIN)_

**Comment by DominiqueMakowski** [comment]
🤩

**Comment by IndrajeetPatil** [comment]
Looks stunning!

**Comment by bwiernik** [comment]
That green/red/blue color scheme works really well for me

**Comment by bwiernik** [comment]
Could the red smoother in the other plots also be blue? Red and black lines are hard for folks with protanopia to distinguish

**Comment by bwiernik** [comment]
> @bwiernik Could you please open a PR and add yourself as contributor to the DESCRIPTION file, if you like?

I'm already there 😃

**Comment by strengejacke** [comment]
Ok, I think the best way is to make it (almost) fully customizable, with sensible defaults. @bwiernik (and others) what do you think about the default colors (first plot)?

``` r
library(performance)
model <- lm(mpg ~ wt + am + gear + vs * cyl, data = mtcars)

# default
check_model(model)
```

![p1](https://user-images.githubusercontent.com/26301769/112963717-ee33a680-9147-11eb-9dda-2bbe7ea06bda.png)

``` r
# custom
check_model(model, colors = see::material_colors(c("blue", "yellow", "red")))
```

![p2](https://user-images.githubusercontent.com/26301769/112963740-f2f85a80-9147-11eb-9133-b99d6dcad486.png)

``` r
# dark theme
check_model(model, colors = see::palette_see("light")(3),
            theme = "see::theme_abyss")
```

![p3](https://user-images.githubusercontent.com/26301769/112963757-f7247800-9147-11eb-811f-ac5bc027dd7b.png)

**Comment by strengejacke** [comment]
(ok, I changed the subtiltes: "green line" is now "reference line", and for VIF, "Blue or red bars" is now "Higher bars (>5)"

**Comment by bwiernik** [comment]
I like the defaults. Thanks!

For the subtitles, I think the revised ones are probably okay. If there was interest in referring to colors, it might be possible to adapt the lookup table from [here](https://www.color-blindness.com/color-name-hue-tool/js/ntc.js) to parse a given color hex code into a one-word verbal color descriptor.
