### ISSUE TITLE
switch to `patchwork` from `gridExtra`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/see#99]
As discussed on Twitter

**Comment by strengejacke** [comment]
It mainly affects the `plots()` method, I'd say.

**Comment by bwiernik** [comment]
This will also make it much easier to handle situations like this for users: https://github.com/easystats/performance/discussions/293

**Comment by bwiernik** [comment]
As part of this, we should also add a `plot()` method to correspond to every `print()` method that returns the composed plot/patchwork object so that the patchwork can be more easily modified.
